// Generated by scripts/build-salary-data.py from the BLS OEWS files. Do not edit by hand.
// Annual wages in US dollars: 10th, 25th, 50th (median), 75th and 90th percentile.

export const DATA_PERIOD = "May 2025";
export const DATA_RELEASED = "2026-05-15";
export const AREA_COUNT = 585;
export const AREA_COUNTS = { states: 51, territories: 3, metros: 393, nonmetros: 137 };

export interface NationalWage {
  title: string;
  p: [number, number, number, number, number];
  mean: number;
  emp: number | null;
  areas: number;
}

export const NATIONAL: Record<string, NationalWage> = {
  "15-1252": { title: "Software Developers", p: [82460, 105210, 135980, 171980, 214670], mean: 148100, emp: 1687890, areas: 566 },
  "15-1254": { title: "Web Developers", p: [48100, 64230, 92650, 126230, 162290], mean: 98770, emp: 70190, areas: 253 },
  "15-1255": { title: "Web and Digital Interface Designers", p: [53750, 73290, 104000, 158820, 201550], mean: 117490, emp: 113330, areas: 252 },
  "15-1253": { title: "Software Quality Assurance Analysts and Testers", p: [61440, 80310, 104300, 133180, 167010], mean: 111490, emp: 186740, areas: 308 },
  "15-1251": { title: "Computer Programmers", p: [57710, 75850, 100390, 130680, 160460], mean: 105170, emp: 92230, areas: 323 },
  "15-1221": { title: "Computer and Information Research Scientists", p: [82200, 103570, 140300, 188700, 230630], mean: 153930, emp: 37200, areas: 113 },
  "17-2061": { title: "Computer Hardware Engineers", p: [92940, 126090, 161740, 202990, 225330], mean: 162670, emp: 76660, areas: 154 },
  "15-1212": { title: "Information Security Analysts", p: [75090, 97810, 129180, 163500, 199850], mean: 132510, emp: 190650, areas: 384 },
  "15-1241": { title: "Computer Network Architects", p: [79900, 104620, 134050, 168200, 202680], mean: 139580, emp: 179740, areas: 372 },
  "15-1244": { title: "Network and Computer Systems Administrators", p: [62640, 78010, 99130, 126640, 155050], mean: 103680, emp: 314340, areas: 565 },
  "15-1211": { title: "Computer Systems Analysts", p: [67340, 82860, 105850, 134110, 167710], mean: 114610, emp: 519530, areas: 550 },
  "15-1242": { title: "Database Administrators", p: [60230, 79610, 104620, 135460, 163320], mean: 110090, emp: 69990, areas: 283 },
  "15-1243": { title: "Database Architects", p: [86240, 109370, 139500, 169290, 204000], mean: 144440, emp: 67140, areas: 193 },
  "15-1231": { title: "Computer Network Support Specialists", p: [47120, 58240, 76220, 98750, 127780], mean: 81870, emp: 146190, areas: 462 },
  "15-1232": { title: "Computer User Support Specialists", p: [40980, 49000, 61860, 79040, 100540], mean: 67330, emp: 717190, areas: 585 },
  "15-1299": { title: "Computer Occupations, All Other", p: [55940, 79370, 116580, 157500, 188470], mean: 122230, emp: 435370, areas: 527 },
  "15-2051": { title: "Data Scientists", p: [67240, 85660, 120230, 158880, 199130], mean: 126800, emp: 262440, areas: 425 },
  "15-2041": { title: "Statisticians", p: [64000, 82220, 105650, 141490, 174050], mean: 115700, emp: 29030, areas: 143 },
  "15-2031": { title: "Operations Research Analysts", p: [57060, 68360, 88940, 125990, 159910], mean: 99730, emp: 108510, areas: 267 },
  "27-1024": { title: "Graphic Designers", p: [39520, 49040, 62960, 81830, 104910], mean: 70560, emp: 197830, areas: 527 },
  "27-3042": { title: "Technical Writers", p: [57440, 70880, 90390, 115510, 145270], mean: 96970, emp: 45500, areas: 211 },
  "27-3043": { title: "Writers and Authors", p: [44310, 58230, 76910, 101950, 139870], mean: 86090, emp: 47940, areas: 204 },
  "27-3031": { title: "Public Relations Specialists", p: [44110, 56260, 74750, 100370, 135150], mean: 84120, emp: 283380, areas: 552 },
  "13-1161": { title: "Market Research Analysts and Marketing Specialists", p: [43390, 58350, 78760, 108310, 155480], mean: 89490, emp: 899580, areas: 579 },
  "11-2021": { title: "Marketing Managers", p: [90260, 123020, 166790, 216410, 293610], mean: 177770, emp: 395240, areas: 503 },
  "11-2022": { title: "Sales Managers", p: [73170, 100360, 148270, 207340, 290540], mean: 164350, emp: 637080, areas: 578 },
  "41-3091": { title: "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel", p: [37980, 47670, 69990, 100480, 148840], mean: 82430, emp: 1256010, areas: 583 },
  "43-4051": { title: "Customer Service Representatives", p: [31750, 36870, 44770, 51780, 63590], mean: 46590, emp: 2595750, areas: 585 },
  "11-3021": { title: "Computer and Information Systems Managers", p: [107550, 138060, 175140, 220730, 297510], mean: 192160, emp: 670570, areas: 572 },
  "11-9041": { title: "Architectural and Engineering Managers", p: [120810, 139360, 171270, 212500, 262760], mean: 181540, emp: 220260, areas: 507 },
  "11-1021": { title: "General and Operations Managers", p: [50090, 72320, 105770, 167280, 253390], mean: 134940, emp: 3503020, areas: 584 },
  "13-1082": { title: "Project Management Specialists", p: [61580, 78440, 102320, 133100, 167970], mean: 110740, emp: 1066670, areas: 579 },
  "13-1111": { title: "Management Analysts", p: [60640, 77950, 101860, 133370, 171640], mean: 113790, emp: 898280, areas: 574 },
  "13-2011": { title: "Accountants and Auditors", p: [56020, 67020, 83680, 109810, 144090], mean: 94750, emp: 1449500, areas: 585 },
  "13-1071": { title: "Human Resources Specialists", p: [47180, 58610, 75940, 99380, 128720], mean: 81990, emp: 912430, areas: 585 },
};
