// Generate text report for clipboard copy
export function generateTextReport(result: WebsiteAuditResult): string {
  return `
WEBSITE AUDIT REPORT
====================
URL: ${result.url}
Domain: ${result.domain}
Scanned: ${result.scannedAt}
Pages: ${result.pagesScanned}
Duration: ${(result.scanDuration / 1000).toFixed(1)}s

OVERALL SCORE: ${result.overallScore}/100 (Grade: ${result.overallScore >= 90 ? 'A+' : result.overallScore >= 80 ? 'A' : result.overallScore >= 70 ? 'B' : result.overallScore >= 60 ? 'C' : result.overallScore >= 50 ? 'D' : 'F'})

CATEGORY SCORES
---------------
${Object.entries(result.scores).map(([cat, score]) => 
  `${cat.toUpperCase()}: ${score.score}/100 (${score.issues} issues, ${score.passedChecks}/${score.totalChecks} checks passed)`
).join('\n')}

ISSUE SEVERITY BREAKDOWN
------------------------
Critical: ${result.issues.filter(i => i.severity === 'critical').length}
High:     ${result.issues.filter(i => i.severity === 'high').length}
Medium:   ${result.issues.filter(i => i.severity === 'medium').length}
Low:      ${result.issues.filter(i => i.severity === 'low').length}

SUMMARY
-------
Strengths:
${result.summary.strengths.slice(0, 8).map(s => `• ${s}`).join('\n')}

Weaknesses:
${result.summary.weaknesses.slice(0, 8).map(w => `• ${w}`).join('\n')}

Opportunities:
${result.summary.opportunities.slice(0, 8).map(o => `• ${o}`).join('\n')}

TOP CRITICAL ISSUES
-------------------
${result.criticalIssues.slice(0, 10).map(issue => 
  `[${issue.severity.toUpperCase()}] ${issue.title}\n  ${issue.suggestion}${issue.timeToFix ? ` (${issue.timeToFix})` : ''}`
).join('\n\n')}

RECOMMENDATIONS
---------------
${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

QUICK WINS
----------
${result.quickWins?.slice(0, 8).map((issue, i) => 
  `${i + 1}. ${issue.title} — ${issue.suggestion}${issue.timeToFix ? ` (${issue.timeToFix})` : ''}`
).join('\n') || 'No quick wins identified.'}

CONTENT ANALYSIS
----------------
Words:         ${result.contentAnalysis.wordCount.toLocaleString()}
Reading Time:  ${result.contentAnalysis.readingTime} min
Readability:   ${result.contentAnalysis.readabilityScore.toFixed(0)}/100 (${result.contentAnalysis.readabilityGrade})
Sentences:     ${result.contentAnalysis.sentenceCount}
Paragraphs:    ${result.contentAnalysis.paragraphCount}
CTAs Found:    ${result.contentAnalysis.ctaCount}
Trust Signals: ${result.contentAnalysis.trustSignals.length}
Sentiment:     ${result.contentAnalysis.sentimentScore > 0 ? 'Positive' : result.contentAnalysis.sentimentScore < 0 ? 'Negative' : 'Neutral'}

Generated by DevelopersMatrix AI Website Audit Tool
https://developersmatrix.com/tools/website-audit
${new Date(result.scannedAt).toLocaleDateString()}
`.trim();
}

// Generate professional HTML report for PDF export
export function generateHTMLReport(result: WebsiteAuditResult): string {
  const grade = result.overallScore >= 90 ? 'A+' : result.overallScore >= 80 ? 'A' : result.overallScore >= 70 ? 'B' : result.overallScore >= 60 ? 'C' : result.overallScore >= 50 ? 'D' : 'F';
  const gradeColor = result.overallScore >= 70 ? '#10b981' : result.overallScore >= 50 ? '#eab308' : '#ef4444';
  
  const severityCounts = {
    critical: result.issues.filter(i => i.severity === 'critical').length,
    high: result.issues.filter(i => i.severity === 'high').length,
    medium: result.issues.filter(i => i.severity === 'medium').length,
    low: result.issues.filter(i => i.severity === 'low').length,
  };

  const scoreBar = (score: number) => {
    const color = score >= 70 ? '#10b981' : score >= 50 ? '#eab308' : '#ef4444';
    return `<div style="width:100%;height:8px;background:#e5e7eb;border-radius:4px;overflow:hidden;"><div style="width:${score}%;height:100%;background:${color};border-radius:4px;"></div></div>`;
  };

  const severityBadge = (severity: string) => {
    const colors: Record<string, string> = {
      critical: '#ef4444',
      high: '#f97316',
      medium: '#eab308',
      low: '#3b82f6',
    };
    return `<span style="display:inline-block;padding:2px 8px;border-radius:4px;background:${colors[severity]};color:white;font-size:10px;font-weight:bold;text-transform:uppercase;">${severity}</span>`;
  };

  const issueHTML = (issue: AuditIssue) => `<div style="margin:12px 0;padding:16px;border-radius:8px;border-left:4px solid ${
    issue.severity === 'critical' ? '#ef4444' : issue.severity === 'high' ? '#f97316' : issue.severity === 'medium' ? '#eab308' : '#3b82f6'
  };background:#f8fafc;">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
      <div style="font-weight:600;font-size:14px;color:#1e293b;">${issue.title}</div>
      <div>${severityBadge(issue.severity)} ${issue.timeToFix ? `<span style="font-size:11px;color:#64748b;margin-left:8px;">${issue.timeToFix}</span>` : ''}</div>
    </div>
    <div style="font-size:13px;color:#475569;margin-bottom:8px;">${issue.description}</div>
    ${issue.impact ? `<div style="font-size:12px;color:#64748b;margin-bottom:8px;"><strong>Impact:</strong> ${issue.impact}</div>` : ''}
    ${issue.affectedUrls && issue.affectedUrls.length > 0 ? `
      <div style="font-size:11px;color:#64748b;margin-bottom:8px;">
        <strong>Affected:</strong> ${issue.affectedUrls.slice(0, 3).join(', ')}${issue.affectedUrls.length > 3 ? ` +${issue.affectedUrls.length - 3} more` : ''}
      </div>
    ` : ''}
    ${issue.codeSnippet ? `
      <div style="margin:8px 0;">
        <div style="font-size:11px;color:#64748b;font-weight:600;margin-bottom:4px;">Code Reference</div>
        <pre style="background:#1e293b;color:#e2e8f0;padding:10px;border-radius:6px;font-size:11px;overflow-x:auto;font-family:monospace;white-space:pre-wrap;">${issue.codeSnippet.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
      </div>
    ` : ''}
    ${issue.fixInstructions && issue.fixInstructions.length > 0 ? `
      <div style="margin-top:8px;">
        <div style="font-size:11px;color:#64748b;font-weight:600;margin-bottom:4px;">How to Fix</div>
        ${issue.fixInstructions.map(step => `
          <div style="display:flex;gap:8px;margin:4px 0;">
            <div style="flex-shrink:0;width:20px;height:20px;border-radius:50%;background:#3b82f6;color:white;font-size:11px;font-weight:bold;display:flex;align-items:center;justify-content:center;">${step.step}</div>
            <div style="font-size:12px;color:#475569;"><strong>${step.title}:</strong> ${step.description}</div>
          </div>
        `).join('')}
      </div>
    ` : ''}
    <div style="font-size:12px;color:#334155;margin-top:8px;padding-top:8px;border-top:1px solid #e2e8f0;">
      <strong>Fix:</strong> ${issue.suggestion}
    </div>
  </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Website Audit Report — ${result.domain}</title>
  <style>
    @page { size: A4; margin: 20mm; }
    @page :first { margin: 0; }
    * { box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1e293b; line-height: 1.6; margin: 0; padding: 0; background: white; }
    .page { page-break-after: always; padding: 40px; }
    .page:last-child { page-break-after: auto; }
    
    /* Cover Page */
    .cover { background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%); color: white; min-height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 60px; page-break-after: always; }
    .cover-brand { font-size: 14px; letter-spacing: 3px; text-transform: uppercase; color: #94a3b8; margin-bottom: 40px; }
    .cover-title { font-size: 42px; font-weight: 800; margin-bottom: 16px; letter-spacing: -1px; }
    .cover-subtitle { font-size: 18px; color: #cbd5e1; margin-bottom: 60px; }
    .cover-domain { font-size: 28px; font-weight: 700; color: #60a5fa; margin-bottom: 8px; word-break: break-all; }
    .cover-date { font-size: 14px; color: #94a3b8; margin-bottom: 50px; }
    .cover-score { width: 180px; height: 180px; border-radius: 50%; border: 8px solid ${gradeColor}; display: flex; flex-direction: column; align-items: center; justify-content: center; margin: 0 auto 20px; }
    .cover-score-value { font-size: 56px; font-weight: 800; color: white; line-height: 1; }
    .cover-score-label { font-size: 13px; color: #94a3b8; text-transform: uppercase; letter-spacing: 2px; margin-top: 4px; }
    .cover-grade { font-size: 72px; font-weight: 800; color: ${gradeColor}; line-height: 1; margin-top: 10px; }
    .cover-meta { display: flex; gap: 40px; justify-content: center; margin-top: 40px; }
    .cover-meta-item { text-align: center; }
    .cover-meta-value { font-size: 24px; font-weight: 700; color: white; }
    .cover-meta-label { font-size: 12px; color: #94a3b8; text-transform: uppercase; letter-spacing: 1px; }
    .cover-footer { position: absolute; bottom: 40px; left: 0; right: 0; text-align: center; font-size: 12px; color: #64748b; }
    
    /* Content Pages */
    h1 { font-size: 28px; font-weight: 700; color: #0f172a; margin: 0 0 24px 0; padding-bottom: 12px; border-bottom: 3px solid #3b82f6; }
    h2 { font-size: 20px; font-weight: 600; color: #1e293b; margin: 32px 0 16px 0; padding-bottom: 8px; border-bottom: 2px solid #e2e8f0; }
    h3 { font-size: 16px; font-weight: 600; color: #334155; margin: 20px 0 10px 0; }
    
    .section-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
    .section-domain { font-size: 14px; color: #64748b; }
    
    .score-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin: 20px 0; }
    .score-item { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 20px; }
    .score-item-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
    .score-item-name { font-size: 14px; font-weight: 600; color: #475569; text-transform: uppercase; letter-spacing: 0.5px; }
    .score-item-value { font-size: 28px; font-weight: 700; }
    .score-item-bar { margin-top: 8px; }
    .score-item-issues { font-size: 12px; color: #64748b; margin-top: 6px; }
    
    .dist-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 20px 0; }
    .dist-item { text-align: center; padding: 16px; border-radius: 10px; }
    .dist-item.critical { background: #fef2f2; border: 1px solid #fecaca; }
    .dist-item.high { background: #fff7ed; border: 1px solid #fed7aa; }
    .dist-item.medium { background: #fefce8; border: 1px solid #fde68a; }
    .dist-item.low { background: #eff6ff; border: 1px solid #bfdbfe; }
    .dist-count { font-size: 32px; font-weight: 700; }
    .dist-label { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
    
    .rec-item { display: flex; gap: 12px; padding: 12px 0; border-bottom: 1px solid #f1f5f9; }
    .rec-number { flex-shrink: 0; width: 28px; height: 28px; border-radius: 50%; background: #3b82f6; color: white; font-size: 13px; font-weight: 700; display: flex; align-items: center; justify-content: center; }
    .rec-text { font-size: 14px; color: #475569; padding-top: 2px; }
    
    .content-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 20px 0; }
    .content-item { text-align: center; padding: 20px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; }
    .content-value { font-size: 28px; font-weight: 700; color: #1e293b; }
    .content-label { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
    
    .report-footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; text-align: center; }
    .report-footer-brand { font-size: 16px; font-weight: 700; color: #1e293b; margin-bottom: 4px; }
    .report-footer-url { font-size: 13px; color: #3b82f6; }
    .report-footer-date { font-size: 12px; color: #94a3b8; margin-top: 4px; }
    
    @media print {
      .page { padding: 20px; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>

  <!-- PAGE 1: COVER -->
  <div class="cover">
    <div class="cover-brand">DevelopersMatrix</div>
    <div class="cover-title">Website Audit Report</div>
    <div class="cover-subtitle">Comprehensive Technical Analysis</div>
    <div class="cover-domain">${result.domain}</div>
    <div class="cover-date">${new Date(result.scannedAt).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
    
    <div class="cover-score">
      <div class="cover-score-value">${result.overallScore}</div>
      <div class="cover-score-label">Overall Score</div>
    </div>
    <div class="cover-grade">${grade}</div>
    
    <div class="cover-meta">
      <div class="cover-meta-item">
        <div class="cover-meta-value">${result.pagesScanned}</div>
        <div class="cover-meta-label">Pages Scanned</div>
      </div>
      <div class="cover-meta-item">
        <div class="cover-meta-value">${result.issues.length}</div>
        <div class="cover-meta-label">Issues Found</div>
      </div>
      <div class="cover-meta-item">
        <div class="cover-meta-value">${result.criticalIssues.length}</div>
        <div class="cover-meta-label">Critical</div>
      </div>
      <div class="cover-meta-item">
        <div class="cover-meta-value">${(result.scanDuration / 1000).toFixed(1)}s</div>
        <div class="cover-meta-label">Scan Time</div>
      </div>
    </div>
    
    <div class="cover-footer">
      developersmatrix.com/tools/website-audit &nbsp;&bull;&nbsp; Free AI-Powered Website Audit Tool
    </div>
  </div>

  <!-- PAGE 2: EXECUTIVE SUMMARY -->
  <div class="page">
    <div class="section-header">
      <h1>Executive Summary</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    
    <p style="font-size:15px;color:#475569;margin-bottom:24px;">
      This report provides a comprehensive technical analysis of <strong>${result.domain}</strong>. 
      The site was audited across 7 categories with ${result.issues.length} total issues identified, 
      including ${result.criticalIssues.length} critical issues requiring immediate attention.
    </p>
    
    <h2>Score Breakdown</h2>
    <div class="score-grid">
      ${Object.entries(result.scores).map(([cat, score]) => `
        <div class="score-item">
          <div class="score-item-header">
            <div class="score-item-name">${cat}</div>
            <div class="score-item-value" style="color:${score.score >= 70 ? '#10b981' : score.score >= 50 ? '#eab308' : '#ef4444'};">${score.score}<span style="font-size:14px;color:#94a3b8;font-weight:400;">/100</span></div>
          </div>
          <div class="score-item-bar">${scoreBar(score.score)}</div>
          <div class="score-item-issues">${score.issues} issues &nbsp;|&nbsp; ${score.passedChecks}/${score.totalChecks} checks passed</div>
        </div>
      `).join('')}
    </div>
    
    <h2>Issue Distribution</h2>
    <div class="dist-grid">
      <div class="dist-item critical">
        <div class="dist-count" style="color:#dc2626;">${severityCounts.critical}</div>
        <div class="dist-label" style="color:#991b1b;">Critical</div>
      </div>
      <div class="dist-item high">
        <div class="dist-count" style="color:#ea580c;">${severityCounts.high}</div>
        <div class="dist-label" style="color:#9a3412;">High</div>
      </div>
      <div class="dist-item medium">
        <div class="dist-count" style="color:#ca8a04;">${severityCounts.medium}</div>
        <div class="dist-label" style="color:#854d0e;">Medium</div>
      </div>
      <div class="dist-item low">
        <div class="dist-count" style="color:#2563eb;">${severityCounts.low}</div>
        <div class="dist-label" style="color:#1e40af;">Low</div>
      </div>
    </div>
    
    <h2>Summary</h2>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;">
      <div style="padding:16px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;">
        <h3 style="color:#15803d;margin:0 0 8px 0;font-size:14px;">✓ Strengths</h3>
        <ul style="margin:0;padding-left:16px;font-size:13px;color:#166534;">
          ${result.summary.strengths.slice(0, 5).map(s => `<li style="margin:4px 0;">${s}</li>`).join('')}
        </ul>
      </div>
      <div style="padding:16px;background:#fef2f2;border:1px solid #fecaca;border-radius:10px;">
        <h3 style="color:#b91c1c;margin:0 0 8px 0;font-size:14px;">✗ Weaknesses</h3>
        <ul style="margin:0;padding-left:16px;font-size:13px;color:#991b1b;">
          ${result.summary.weaknesses.slice(0, 5).map(w => `<li style="margin:4px 0;">${w}</li>`).join('')}
        </ul>
      </div>
      <div style="padding:16px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;">
        <h3 style="color:#1d4ed8;margin:0 0 8px 0;font-size:14px;">→ Opportunities</h3>
        <ul style="margin:0;padding-left:16px;font-size:13px;color:#1e40af;">
          ${result.summary.opportunities.slice(0, 5).map(o => `<li style="margin:4px 0;">${o}</li>`).join('')}
        </ul>
      </div>
    </div>
  </div>

  <!-- PAGE 3+: DETAILED ISSUES BY SEVERITY -->
  <div class="page">
    <div class="section-header">
      <h1>Critical Issues</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    <p style="font-size:14px;color:#64748b;margin-bottom:20px;">Fix these first. Critical issues have the highest impact on SEO, security, and user experience.</p>
    ${result.issues.filter(i => i.severity === 'critical').map(issueHTML).join('') || '<p style="color:#10b981;font-size:14px;">✓ No critical issues found!</p>'}
  </div>

  <div class="page">
    <div class="section-header">
      <h1>High Priority Issues</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    <p style="font-size:14px;color:#64748b;margin-bottom:20px;">These issues significantly impact performance and should be addressed soon after critical fixes.</p>
    ${result.issues.filter(i => i.severity === 'high').map(issueHTML).join('') || '<p style="color:#10b981;font-size:14px;">✓ No high priority issues found!</p>'}
  </div>

  <div class="page">
    <div class="section-header">
      <h1>Medium Priority Issues</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    <p style="font-size:14px;color:#64748b;margin-bottom:20px;">These are recommended improvements that will enhance your site over time.</p>
    ${result.issues.filter(i => i.severity === 'medium').map(issueHTML).join('') || '<p style="color:#10b981;font-size:14px;">✓ No medium priority issues found!</p>'}
  </div>

  <div class="page">
    <div class="section-header">
      <h1>Low Priority Improvements</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    <p style="font-size:14px;color:#64748b;margin-bottom:20px;">Minor optimizations and best-practice suggestions.</p>
    ${result.issues.filter(i => i.severity === 'low').map(issueHTML).join('') || '<p style="color:#10b981;font-size:14px;">✓ No low priority issues found!</p>'}
  </div>

  <!-- PAGE: RECOMMENDATIONS -->
  <div class="page">
    <div class="section-header">
      <h1>Recommendations</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    <p style="font-size:14px;color:#64748b;margin-bottom:20px;">Prioritized action items to improve your website.</p>
    ${result.recommendations.map((r, i) => `
      <div class="rec-item">
        <div class="rec-number">${i + 1}</div>
        <div class="rec-text">${r}</div>
      </div>
    `).join('')}
    
    <h2>Quick Wins</h2>
    <p style="font-size:14px;color:#64748b;margin-bottom:16px;">High impact fixes that take under 15 minutes.</p>
    ${result.quickWins && result.quickWins.length > 0 ? result.quickWins.slice(0, 8).map((issue, i) => `
      <div class="rec-item">
        <div class="rec-number" style="background:#10b981;">${i + 1}</div>
        <div class="rec-text"><strong>${issue.title}</strong> — ${issue.suggestion} ${issue.timeToFix ? `<span style="color:#64748b;">(${issue.timeToFix})</span>` : ''}</div>
      </div>
    `).join('') : '<p style="color:#64748b;font-size:14px;">No quick wins identified.</p>'}
  </div>

  <!-- PAGE: CONTENT ANALYSIS -->
  <div class="page">
    <div class="section-header">
      <h1>Content Analysis</h1>
      <div class="section-domain">${result.domain}</div>
    </div>
    
    <div class="content-grid">
      <div class="content-item">
        <div class="content-value">${result.contentAnalysis.wordCount.toLocaleString()}</div>
        <div class="content-label">Total Words</div>
      </div>
      <div class="content-item">
        <div class="content-value">${result.contentAnalysis.readingTime}</div>
        <div class="content-label">Minutes to Read</div>
      </div>
      <div class="content-item">
        <div class="content-value">${result.contentAnalysis.readabilityScore.toFixed(0)}</div>
        <div class="content-label">Readability Score</div>
      </div>
      <div class="content-item">
        <div class="content-value">${result.contentAnalysis.sentenceCount}</div>
        <div class="content-label">Sentences</div>
      </div>
      <div class="content-item">
        <div class="content-value">${result.contentAnalysis.paragraphCount}</div>
        <div class="content-label">Paragraphs</div>
      </div>
      <div class="content-item">
        <div class="content-value">${result.contentAnalysis.ctaCount}</div>
        <div class="content-label">CTAs Found</div>
      </div>
    </div>
    
    <h2>Readability Grade</h2>
    <div style="display:flex;align-items:center;gap:16px;margin:16px 0;">
      <div style="font-size:48px;font-weight:800;color:${result.contentAnalysis.readabilityScore >= 60 ? '#10b981' : result.contentAnalysis.readabilityScore >= 40 ? '#eab308' : '#ef4444'};">${result.contentAnalysis.readabilityGrade}</div>
      <div style="font-size:14px;color:#64748b;">
        ${result.contentAnalysis.readabilityScore >= 60 ? 'Easy to read. Suitable for a broad audience.' : result.contentAnalysis.readabilityScore >= 40 ? 'Moderate complexity. May require some effort.' : 'Difficult to read. Consider simplifying.'}
      </div>
    </div>
    
    <h2>Sentiment</h2>
    <p style="font-size:14px;color:#475569;">
      ${result.contentAnalysis.sentimentScore > 0 ? `<span style="color:#10b981;font-weight:600;">Positive (${result.contentAnalysis.sentimentScore > 5 ? 'Strongly' : 'Moderately'})</span>` : result.contentAnalysis.sentimentScore < 0 ? `<span style="color:#ef4444;font-weight:600;">Negative</span>` : `<span style="color:#64748b;">Neutral</span>`}
      — The content tone is ${result.contentAnalysis.sentimentScore > 0 ? 'optimistic and encouraging' : result.contentAnalysis.sentimentScore < 0 ? 'critical or cautionary' : 'balanced and factual'}.
    </p>
  </div>

  <!-- FINAL PAGE: FOOTER / BRANDING -->
  <div class="page" style="display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;min-height:60vh;">
    <div style="font-size:24px;font-weight:800;color:#1e293b;margin-bottom:8px;">DevelopersMatrix</div>
    <div style="font-size:14px;color:#64748b;margin-bottom:24px;">Free AI-Powered Website Audit Tool</div>
    
    <div style="width:80px;height:4px;background:linear-gradient(90deg,#3b82f6,#8b5cf6);border-radius:2px;margin-bottom:24px;"></div>
    
    <p style="font-size:14px;color:#475569;max-width:400px;margin-bottom:24px;">
      This report was generated automatically by DevelopersMatrix AI Website Audit.
      Run your own free audit at:
    </p>
    
    <div style="font-size:16px;font-weight:600;color:#3b82f6;margin-bottom:32px;">
      developersmatrix.com/tools/website-audit
    </div>
    
    <div style="font-size:12px;color:#94a3b8;">
      Report generated on ${new Date(result.scannedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}<br>
      ${result.pagesScanned} pages scanned in ${(result.scanDuration / 1000).toFixed(1)} seconds
    </div>
  </div>

</body>
</html>`.trim();
}