import type { BankQuestion } from './bank-types';

// Technical questions for engineering roles. Every question has a short list of
// key points a strong answer covers, and a model answer written for this site.

export const TECHNICAL_ENGINEERING: BankQuestion[] = [
  // ---------------------------------------------------------------- Frontend
  {
    id: 'fe-var-let-const',
    roles: ['frontend-developer', 'fullstack-developer', 'software-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is the difference between var, let and const in JavaScript?',
    anchors: 'var|let|const',
    points: [
      { label: 'Scope: var is function scoped, let and const are block scoped', terms: 'block scope|block scoped|function scope|function scoped|scoped to the block|scoped to the function' },
      { label: 'Hoisting and the temporal dead zone', terms: 'hoist|hoisted|hoisting|temporal dead zone|tdz|before declaration|before it is declared' },
      { label: 'const cannot be reassigned, but objects can still be mutated', terms: 'reassign|reassigned|cannot be reassigned|mutate|mutated|binding|the object itself|properties can change' },
      { label: 'A sensible default: const first, let when needed, avoid var', terms: 'prefer const|default to const|use const|use let when|avoid var|never use var|by default' },
    ],
    model:
      'var is function scoped and hoisted with the value undefined, so you can read it before its declaration line. let and const are block scoped and are also hoisted, but sit in the temporal dead zone until the declaration runs, so reading them early throws. const stops reassignment of the binding, but the object it points to can still change, so a const array can be pushed to. My default is const, let only when the value really changes, such as a loop counter, and no var in new code.',
    hints: ['Cover scope, hoisting and reassignment.', 'Give one small example for const with an object.'],
    next: 'What does this print, and why: a for loop with var i and a setTimeout that logs i?',
  },
  {
    id: 'fe-useeffect',
    roles: ['frontend-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How does useEffect work in React, and what are the most common mistakes people make with it?',
    anchors: 'useeffect|effect|react|component|render|lifecycle',
    points: [
      { label: 'The effect runs after the component renders', terms: 'after render|after rendering|after the render|after paint|after the component renders|after mount|after it mounts' },
      { label: 'The dependency array controls when it runs again', terms: 'dependency array|dependencies|deps|re run|rerun|runs again|when the values change|empty array' },
      { label: 'The cleanup function and when it runs', terms: 'cleanup|clean up|return a function|unsubscribe|clearinterval|cleartimeout|abort|on unmount|before the next effect' },
      { label: 'Named real pitfalls such as stale values or infinite loops', terms: 'stale closure|stale value|infinite loop|missing dependency|exhaustive deps|race condition|set state after unmount|object in dependency' },
      { label: 'Knew when an effect is not needed at all', terms: 'not need an effect|do not need|derive|derived|compute during render|event handler|usememo' },
    ],
    model:
      'useEffect runs after React has rendered and painted, so it is for syncing with things outside React, such as subscriptions, timers or fetching. The dependency array decides when it runs again: no array means every render, an empty array means once after mount, and values in the array mean whenever those change. If the effect returns a function, React calls it before the next run and on unmount, which is where you unsubscribe or clear timers. Common mistakes are missing dependencies that leave stale values, setting state inside an effect that depends on that state and loops forever, and using an effect for data you could simply calculate during render.',
    hints: ['Explain when it runs, the dependency array, and cleanup.', 'Name two concrete mistakes.'],
    next: 'How would you cancel an in flight fetch when the component unmounts?',
  },
  {
    id: 'fe-web-vitals',
    roles: ['frontend-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'A landing page loads slowly on mobile. How would you find the cause and improve its Core Web Vitals?',
    anchors: 'core web vitals|lcp|cls|inp|performance|slow|load|loading|page speed|lighthouse',
    points: [
      { label: 'Measure first with real tools and field data', terms: 'lighthouse|pagespeed|web vitals|performance tab|devtools|field data|crux|search console|measure|profile' },
      { label: 'Fix Largest Contentful Paint: hero image, server time, render blocking', terms: 'lcp|largest contentful paint|hero image|preload|fetchpriority|priority|webp|avif|compress|render blocking|ttfb' },
      { label: 'Reduce JavaScript: code splitting, deferring, removing unused code', terms: 'code split|code splitting|lazy load|bundle|defer|async script|tree shak|dynamic import|third party|unused' },
      { label: 'Prevent layout shift', terms: 'cls|layout shift|width and height|aspect ratio|reserve space|font display|placeholder' },
      { label: 'Keep interactions responsive', terms: 'inp|interaction to next paint|main thread|long task|debounce|web worker|hydration' },
      { label: 'Caching and a CDN', terms: 'cdn|cache|caching|edge' },
    ],
    model:
      'I would start with PageSpeed Insights for field data and Lighthouse on a throttled mobile profile to see which metric fails. For LCP I check what the LCP element is; usually a hero image, so I serve it in a modern format at the right size, preload it with high priority and make sure nothing hides it until JavaScript runs. For JavaScript weight I split the bundle by route, defer third party scripts and remove unused code. For CLS I give images and embeds fixed dimensions. For INP I look for long tasks on the main thread. Then I measure again rather than assume.',
    hints: ['Start with how you would measure.', 'Then go metric by metric: LCP, CLS, INP.'],
    next: 'Lab results are fine but field data is poor. Why might that be?',
  },
  {
    id: 'fe-event-delegation',
    roles: ['frontend-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is event delegation in JavaScript, and why would you use it?',
    anchors: 'event delegation|delegation|event|listener|bubbl',
    points: [
      { label: 'Events bubble up from the target to its ancestors', terms: 'bubble|bubbles|bubbling|propagat|up the dom|up the tree' },
      { label: 'One listener on a parent element instead of many', terms: 'parent|ancestor|single listener|one listener|container|attach to the list' },
      { label: 'Use event.target or closest to find the clicked item', terms: 'event target|e target|target|closest|matches|dataset' },
      { label: 'Benefits: fewer listeners and works for elements added later', terms: 'performance|memory|fewer listeners|dynamic|added later|new items|future elements' },
    ],
    model:
      'Most DOM events bubble from the element that was clicked up through its ancestors. Event delegation uses that: instead of adding a click listener to every row in a list, you add one listener to the list and check event.target, usually with closest, to find which row was clicked. It uses less memory, and it automatically works for rows added later, which is handy for lists that update. The catch is that a few events, such as focus, do not bubble, so you use focusin instead.',
    hints: ['Explain bubbling first.', 'Show how you find the clicked element.'],
    next: 'How would stopPropagation affect a delegated listener?',
  },
  {
    id: 'fe-state-location',
    roles: ['frontend-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'In a React application, how do you decide where a piece of state should live?',
    anchors: 'state|usestate|context|redux|store|react',
    points: [
      { label: 'Keep state local when only one component needs it', terms: 'local state|usestate|component state|keep it local|closest' },
      { label: 'Lift state to the nearest common parent when siblings share it', terms: 'lift state|lifting state|common parent|shared parent|prop drilling|pass down' },
      { label: 'Treat server data separately with a fetching and caching library', terms: 'server state|react query|tanstack|swr|apollo|cache|fetching|remote data' },
      { label: 'Use context or a store only for truly global state', terms: 'context|usecontext|provider|redux|zustand|global|store' },
      { label: 'Consider the URL for state that should survive a reload or be shareable', terms: 'url|query param|search param|route param|shareable' },
      { label: 'Mention the cost: re renders and complexity', terms: 're render|rerender|re renders|performance|complexity|trade off|tradeoff' },
    ],
    model:
      'I start as local as possible: if only one component uses it, it stays in useState there. If siblings need it, I lift it to their nearest common parent. Data that comes from the server is not really app state, so I keep it in something like TanStack Query, which handles caching and refetching. Filters, tabs and pagination often belong in the URL so a link reproduces the view. Context or a store like Zustand is for state that many distant parts truly share, such as the signed in user, because every consumer re renders when it changes.',
    hints: ['Go from most local to most global.', 'Mention server state as its own thing.'],
    next: 'Context is causing too many re renders. What would you do?',
  },
  {
    id: 'fe-accessibility',
    roles: ['frontend-developer', 'fullstack-developer', 'mobile-developer'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'How do you make sure an interface you build is accessible?',
    anchors: 'accessib|a11y|screen reader|keyboard|wcag|aria|contrast',
    points: [
      { label: 'Semantic elements first', terms: 'semantic|button element|native element|landmark|heading|nav|main|label element' },
      { label: 'Everything works with a keyboard and focus is visible', terms: 'keyboard|tab order|focus|focus visible|focus trap|tabindex' },
      { label: 'Text alternatives and labels', terms: 'alt text|alt attribute|label|aria label|aria|accessible name' },
      { label: 'Colour contrast and not relying on colour alone', terms: 'contrast|colour|color|wcag|4 5 1' },
      { label: 'Testing with tools and a screen reader', terms: 'screen reader|axe|lighthouse|nvda|voiceover|talkback|jaws|test' },
    ],
    model:
      'I start with semantic HTML, because a real button or label gives keyboard and screen reader support for free, and I only reach for ARIA when no native element fits. I check that every action works with the keyboard alone, in a sensible order, with a visible focus style. Images get meaningful alt text and form fields get real labels. I keep text contrast at WCAG AA, which is 4.5 to 1 for body text, and never use colour as the only signal. Then I run axe in CI and do a quick pass with VoiceOver or NVDA on key flows.',
    hints: ['Think semantics, keyboard, labels, contrast and testing.'],
    next: 'How would you make a custom dropdown menu accessible?',
  },

  // ----------------------------------------------------------------- Backend
  {
    id: 'be-indexing',
    roles: ['backend-developer', 'fullstack-developer', 'software-developer', 'data-analyst'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Explain how a database index speeds up queries, and when adding an index can hurt.',
    anchors: 'index|indexes|indices|indexing|query|database',
    points: [
      { label: 'An index is a separate sorted structure, usually a B tree', terms: 'b tree|btree|b+ tree|sorted|data structure|separate structure|lookup|hash index' },
      { label: 'It avoids a full table scan for filters, joins and sorting', terms: 'full table scan|full scan|scan every row|where clause|join|order by|seek|faster read' },
      { label: 'It slows down writes and uses storage', terms: 'slower write|slows writes|insert|update|delete|write overhead|storage|disk space|maintain' },
      { label: 'Column order and selectivity matter for composite indexes', terms: 'selectivity|cardinality|composite|multi column|column order|leftmost' },
      { label: 'Check the query plan instead of guessing', terms: 'explain|query plan|execution plan|analyze' },
    ],
    model:
      'An index is a separate structure, usually a B tree, that keeps a column sorted with pointers to the rows, so the database can jump to matching rows instead of scanning the whole table. It helps WHERE filters, joins and ORDER BY on the indexed columns. The cost is that every insert, update and delete must also update each index, and indexes use storage, so over indexing slows write heavy tables. For composite indexes the column order matters, because the index is only usable from the leftmost column. I always confirm with EXPLAIN that the planner actually uses it.',
    hints: ['Explain what an index is physically.', 'Then cover the write cost and how you would verify.'],
    next: 'A query has an index on the column but still does a full scan. Why might that happen?',
  },
  {
    id: 'be-rest-graphql',
    roles: ['backend-developer', 'fullstack-developer', 'frontend-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'Compare REST and GraphQL. When would you choose each one?',
    anchors: 'rest|graphql|api|endpoint',
    points: [
      { label: 'REST exposes resources at URLs with HTTP methods', terms: 'resource|endpoint|url|http method|http verb|get|post|put|delete' },
      { label: 'GraphQL has one endpoint and a schema where the client picks fields', terms: 'single endpoint|one endpoint|schema|query|resolver|client specifies|exact fields|ask for' },
      { label: 'Over fetching and under fetching', terms: 'over fetch|overfetch|under fetch|underfetch|too much data|multiple requests|round trip' },
      { label: 'Caching and tooling differences', terms: 'http cach|cache|caching|cdn|tooling|complexity|n+1|dataloader' },
      { label: 'A clear rule for when to pick which', terms: 'when|choose|i would use|pick|depends|public api|mobile|many clients' },
    ],
    model:
      'REST models resources as URLs and uses HTTP methods, so it is simple and works well with HTTP caching and CDNs. GraphQL exposes one endpoint with a typed schema and lets the client ask for exactly the fields it needs, which removes over fetching and the need for several round trips. The cost is more server complexity: you need to guard against expensive queries and the N plus one problem, usually with DataLoader, and caching is harder. I pick REST for simple or public APIs and GraphQL when several clients, such as web and mobile, need different shapes of the same data.',
    hints: ['Explain how each one works, then the trade offs.'],
    next: 'How would you stop a client sending a very expensive GraphQL query?',
  },
  {
    id: 'be-idempotency',
    roles: ['backend-developer', 'fullstack-developer', 'system-architect'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'What does it mean for an API endpoint to be idempotent, and how would you make a payment endpoint idempotent?',
    anchors: 'idempot|retry|duplicate|payment|charge',
    points: [
      { label: 'Defined idempotent: repeating the request has the same effect as once', terms: 'same result|same effect|multiple times|more than once|repeat|only once|exactly once' },
      { label: 'Explained why: retries after timeouts can cause duplicates', terms: 'retry|retries|timeout|network failure|double charge|duplicate|resend' },
      { label: 'Use an idempotency key sent by the client', terms: 'idempotency key|request id|unique key|unique id|client generated|uuid' },
      { label: 'Store the key and the result, enforced by a unique constraint', terms: 'store|save|database|unique constraint|unique index|return the same response|cached response' },
      { label: 'Knows which HTTP methods are idempotent by definition', terms: 'put|delete|get|post is not|not idempotent' },
    ],
    model:
      'An idempotent operation has the same effect whether it runs once or five times. It matters because clients retry after timeouts, and for payments a retry must never charge twice. GET, PUT and DELETE are idempotent by definition, POST is not, so for a payment POST the client sends an idempotency key, a UUID generated once per payment attempt. The server stores the key with the outcome under a unique constraint. If the same key arrives again, it returns the stored response instead of charging again. Keys expire after a sensible window, such as 24 hours.',
    hints: ['Define it, then explain why retries make it necessary.'],
    next: 'Two requests with the same key arrive at the same moment. How do you stop both charging?',
  },
  {
    id: 'be-acid',
    roles: ['backend-developer', 'fullstack-developer', 'software-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What does ACID mean for database transactions? Give an example.',
    anchors: 'acid|transaction|atomic|isolation|durab|consisten',
    points: [
      { label: 'Atomicity: all or nothing', terms: 'atomic|atomicity|all or nothing|either all|rolled back|rollback' },
      { label: 'Consistency: the database moves between valid states', terms: 'consistency|consistent|constraint|valid state|rules' },
      { label: 'Isolation: concurrent transactions do not interfere', terms: 'isolation|concurrent|isolation level|dirty read|serializable|read committed|repeatable read' },
      { label: 'Durability: committed data survives a crash', terms: 'durab|survive|crash|persist|write ahead|wal|disk' },
      { label: 'Gave a concrete example', terms: 'transfer|bank|account|order|example|for example|money' },
    ],
    model:
      'ACID describes what a transaction guarantees. Atomicity means all of its steps happen or none do: moving 100 dollars between two accounts never leaves the money debited but not credited. Consistency means it only moves the database from one valid state to another, respecting constraints such as a balance never going negative. Isolation means two transfers running at the same time behave as if they ran one after the other, depending on the isolation level. Durability means once the transfer commits it survives a crash, because it was written to the write ahead log first.',
    hints: ['Cover all four letters.', 'Use one example, such as a bank transfer, for all four.'],
    next: 'What problems can happen at the Read Committed isolation level?',
  },
  {
    id: 'be-caching',
    roles: ['backend-developer', 'fullstack-developer', 'system-architect', 'software-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How would you add caching to a slow, read heavy API, and how do you keep the cache correct?',
    anchors: 'cache|caching|redis|memcached|cdn',
    points: [
      { label: 'Where the cache lives: Redis, in memory, or a CDN', terms: 'redis|memcached|in memory|cdn|application cache|edge' },
      { label: 'The pattern, such as cache aside', terms: 'cache aside|read through|write through|write behind|lazy load|check the cache first' },
      { label: 'Expiry and invalidation on writes', terms: 'ttl|expire|expiry|expiration|invalidat|evict|delete the key|on update' },
      { label: 'Accepting some staleness, or not', terms: 'stale|staleness|consistency|eventual|fresh' },
      { label: 'Protecting the database from a stampede', terms: 'stampede|thundering herd|dogpile|lock|jitter|single flight|request coalescing' },
      { label: 'Measuring the hit rate', terms: 'hit rate|hit ratio|miss|metrics|monitor' },
    ],
    model:
      'For a read heavy endpoint I would use cache aside with Redis: check Redis first, on a miss read the database, then store the result with a TTL. On writes I delete the affected keys, so the next read refills them, and the TTL is a safety net for anything I miss. I agree with the product owner how stale the data may be, because that decides the TTL. To avoid a stampede when a hot key expires, I add jitter to TTLs and let only one request rebuild a key. Then I watch the hit rate to check the cache is worth it.',
    hints: ['Say where the cache sits and the read and write flow.', 'Then explain invalidation.'],
    next: 'A cached value is wrong for some users after a deploy. How do you find out why?',
  },
  {
    id: 'be-race-condition',
    roles: ['backend-developer', 'fullstack-developer', 'system-architect'],
    category: 'technical',
    levels: ['senior', 'mid'],
    question: 'Two users try to book the last seat on a flight at the same moment. How do you make sure only one succeeds?',
    anchors: 'seat|book|booking|race|concurren|same time|lock|double',
    points: [
      { label: 'Named the problem: a race condition between read and write', terms: 'race condition|race|concurrent|same time|read then write|check then act|double booking' },
      { label: 'An atomic conditional update in the database', terms: 'atomic|conditional update|where seats|where available|update where|decrement|affected rows|rows updated' },
      { label: 'Or row locking inside a transaction', terms: 'select for update|row lock|lock the row|pessimistic|transaction' },
      { label: 'Or optimistic locking with a version number', terms: 'optimistic|version|compare and swap|cas|retry' },
      { label: 'A unique constraint as the final guard', terms: 'unique constraint|unique index|constraint' },
      { label: 'User experience: holds that expire', terms: 'hold|reserve|reservation|expire|timeout|minutes' },
    ],
    model:
      'This is a check then act race: both requests read one free seat, then both write. The simplest fix is to make the check and the write one atomic statement, such as UPDATE seats SET booked_by = user WHERE id = 42 AND booked_by IS NULL, then look at the number of rows updated; only one request gets 1. Alternatives are SELECT FOR UPDATE inside a transaction, or optimistic locking with a version column and a retry. I would also keep a unique constraint on seat and flight as a last guard, and hold a seat for a few minutes during checkout.',
    hints: ['Explain why it fails first.', 'Then give at least one database level fix.'],
    next: 'How would this change if seats were held in Redis instead of the database?',
  },

  // ------------------------------------------------------------ Full stack
  {
    id: 'fs-url-enter',
    roles: ['fullstack-developer', 'software-developer', 'frontend-developer', 'backend-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What happens, step by step, when you type a URL into a browser and press Enter?',
    anchors: 'dns|browser|url|http|request|server|tcp|tls',
    points: [
      { label: 'DNS turns the domain into an IP address', terms: 'dns|ip address|resolve|resolver|lookup' },
      { label: 'A TCP connection and TLS handshake for HTTPS', terms: 'tcp|tls|ssl|handshake|https|certificate' },
      { label: 'The browser sends an HTTP request and gets a response', terms: 'http request|get request|request|response|status code|headers' },
      { label: 'The server side: CDN, load balancer, application, database', terms: 'server|cdn|load balancer|backend|application|database' },
      { label: 'The browser parses HTML and CSS, runs JavaScript and paints', terms: 'parse|dom|cssom|render|paint|layout|javascript' },
    ],
    model:
      'The browser first checks its caches, then asks DNS to resolve the domain to an IP address. It opens a TCP connection to that address and, for HTTPS, performs a TLS handshake that checks the certificate and agrees keys. It sends an HTTP GET request with headers such as cookies. The request may hit a CDN or a load balancer, which forwards it to an application server that might query a database and return HTML. The browser parses the HTML into the DOM, fetches CSS, scripts and images, builds the render tree, lays it out and paints it.',
    hints: ['Go in order: DNS, connection, request, server, rendering.'],
    next: 'Where in that chain would you look first if a page suddenly became slow?',
  },
  {
    id: 'fs-auth-spa',
    roles: ['fullstack-developer', 'backend-developer', 'frontend-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How would you handle user authentication between a single page app and its API?',
    anchors: 'auth|login|session|token|jwt|cookie',
    points: [
      { label: 'Session cookie or token based, and the difference', terms: 'session|cookie|jwt|token|bearer' },
      { label: 'Where the credential is stored and the XSS risk', terms: 'httponly|http only|secure flag|local storage|localstorage|xss|javascript cannot read' },
      { label: 'CSRF protection', terms: 'csrf|samesite|same site|csrf token' },
      { label: 'Expiry, refresh and logout', terms: 'expire|expiry|expiration|refresh token|rotation|revoke|logout' },
      { label: 'HTTPS and safe password storage', terms: 'https|hash|hashed|bcrypt|argon|salt' },
    ],
    model:
      'For a first party SPA on the same site I prefer a server session with an HttpOnly, Secure, SameSite cookie, because JavaScript cannot read it, which limits the damage of an XSS bug. SameSite plus a CSRF token for state changing requests handles cross site forgery. If tokens are needed, for example for mobile clients, I use short lived access tokens and rotating refresh tokens, with the refresh token in an HttpOnly cookie rather than localStorage. Passwords are hashed with bcrypt or Argon2, everything is served over HTTPS, and logout revokes the session on the server.',
    hints: ['Explain where the credential lives and why.', 'Mention XSS and CSRF.'],
    next: 'How would you log a user out on every device at once?',
  },
  {
    id: 'fs-sync-state',
    roles: ['fullstack-developer', 'frontend-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'After a user edits a record, how do you keep what the client shows in sync with the server?',
    anchors: 'sync|server|client|cache|mutation|update|refetch',
    points: [
      { label: 'Invalidate or refetch the affected data after the change', terms: 'invalidate|refetch|revalidate|reload|fetch again' },
      { label: 'Optimistic updates with rollback on error', terms: 'optimistic|roll back|rollback|revert|undo' },
      { label: 'A data fetching library manages the cache', terms: 'react query|tanstack|swr|apollo|rtk query|cache' },
      { label: 'Real time updates for other users', terms: 'websocket|server sent|sse|polling|subscription|real time|push' },
      { label: 'Handling conflicting edits', terms: 'conflict|version|etag|last write wins|concurrent edit|merge' },
    ],
    model:
      'I use a data library such as TanStack Query, so after a mutation I invalidate the queries that include that record and they refetch. For fast feeling edits I apply an optimistic update to the cache straight away and roll it back if the request fails. When other people can edit the same data, I push changes over a WebSocket or SSE, or poll for less critical screens. To avoid silently overwriting someone else, each record carries a version or ETag, and the server rejects stale updates so the client can show a conflict message.',
    hints: ['Cover your own edits first, then other users’ edits.'],
    next: 'An optimistic update succeeds but the server changed another field. How do you reconcile?',
  },
  {
    id: 'fs-testing',
    roles: ['fullstack-developer', 'software-developer', 'qa-engineer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'How would you structure the automated tests for a new full stack feature?',
    anchors: 'test|tests|testing|unit|integration|e2e|end to end',
    points: [
      { label: 'Unit tests for logic', terms: 'unit test|unit tests|unit' },
      { label: 'Integration tests for the API and database together', terms: 'integration|api test|database|test database|endpoint' },
      { label: 'A few end to end tests for the main user journey', terms: 'end to end|e2e|playwright|cypress|selenium|user journey|happy path' },
      { label: 'The balance: many fast tests, few slow ones', terms: 'pyramid|more unit|fewer e2e|few end to end|fast|slow|balance' },
      { label: 'Run them automatically on every change', terms: 'ci|pipeline|pull request|every commit|github actions|automat' },
    ],
    model:
      'I follow the test pyramid. Business logic gets fast unit tests, including edge cases. The API gets integration tests that run against a real test database, checking validation, permissions and responses. Then one or two end to end tests in Playwright cover the main journey, such as a user creating and editing the record, because they are slow and more brittle. All of them run in CI on every pull request, so a change cannot merge with failing tests.',
    hints: ['Name the levels and what each one is for.'],
    next: 'One of your end to end tests fails randomly once in twenty runs. What do you do?',
  },
  {
    id: 'fs-pagination',
    roles: ['fullstack-developer', 'backend-developer'],
    category: 'technical',
    levels: ['mid'],
    question: 'How would you paginate an API that returns a very large, frequently changing list?',
    anchors: 'paginat|page|cursor|offset|limit',
    points: [
      { label: 'Offset and limit pagination and its weaknesses', terms: 'offset|limit|page number|skip' },
      { label: 'Cursor or keyset pagination', terms: 'cursor|keyset|seek|after id|after the last|next token' },
      { label: 'Why: deep pages are slow and items shift', terms: 'slow|deep page|skip rows|duplicate|missing items|shift|inserted|consistent' },
      { label: 'A stable sort with a tie breaker and an index', terms: 'order by|sort|tie breaker|unique|index' },
      { label: 'Page size limits', terms: 'page size|max|maximum|limit the' },
    ],
    model:
      'Offset pagination is simple but has two problems on a large, changing list: OFFSET 100000 still makes the database walk past those rows, and when new items are inserted, users see duplicates or miss items. I would use cursor pagination instead: sort by a stable key such as created_at plus id as a tie breaker, return a cursor encoding the last item, and query WHERE (created_at, id) < cursor ORDER BY created_at DESC, id DESC LIMIT 50. That uses an index, stays fast on deep pages and does not shift. I also cap the page size.',
    hints: ['Compare offset and cursor approaches.'],
    next: 'How would you support jumping directly to page 40 with cursor pagination?',
  },
  {
    id: 'fs-zero-downtime-migration',
    roles: ['fullstack-developer', 'backend-developer', 'devops-engineer', 'system-architect'],
    category: 'technical',
    levels: ['senior'],
    question: 'How would you rename a heavily used database column without any downtime?',
    anchors: 'column|migration|schema|rename|database|downtime',
    points: [
      { label: 'Expand and contract, keeping old and new code compatible', terms: 'expand and contract|expand contract|parallel change|backward compatible|backwards compatible|both versions' },
      { label: 'Add the new column first', terms: 'add the new column|add a new column|new column' },
      { label: 'Write to both and backfill in batches', terms: 'dual write|write to both|backfill|batches|copy data' },
      { label: 'Switch reads, then remove the old column later', terms: 'switch reads|read from the new|drop the old|remove the old|later release' },
      { label: 'Avoid long table locks and keep a rollback path', terms: 'lock|batch|online|rollback|roll back|feature flag' },
    ],
    model:
      'I would never rename in one step, because old application servers still use the old name during a deploy. I use expand and contract. First add the new column, nullable. Deploy code that writes to both columns. Backfill old rows in small batches to avoid long locks. Deploy code that reads from the new column, behind a flag so I can switch back. Once everything is stable, stop writing the old column, and in a later release drop it. Each step is safe to run while the previous version of the app is still live.',
    hints: ['Think about old and new code running at the same time.'],
    next: 'How would you verify the backfill copied every row correctly?',
  },

  // ------------------------------------------------------ Software developer
  {
    id: 'sd-process-thread',
    roles: ['software-developer', 'backend-developer', 'system-architect'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is the difference between a process and a thread?',
    anchors: 'process|thread',
    points: [
      { label: 'Processes have separate memory; threads share their process memory', terms: 'own memory|separate memory|address space|share memory|shared memory|same memory' },
      { label: 'Threads are lighter to create and switch between', terms: 'lightweight|lighter|heavier|context switch|overhead|cheaper' },
      { label: 'Processes talk through IPC', terms: 'ipc|inter process|pipe|socket|message' },
      { label: 'Shared memory means race conditions and locks', terms: 'race condition|synchroniz|lock|mutex|thread safe' },
      { label: 'Isolation: a crashing process does not take others down', terms: 'crash|isolation|isolated|one thread crash|bring down' },
    ],
    model:
      'A process is a running program with its own memory space, so processes are isolated from each other and need inter process communication, such as pipes or sockets, to share data. A thread runs inside a process and shares that process memory with its other threads. That makes threads cheaper to create and switch between, and sharing data is easy, but it also means race conditions, so shared data needs locks or other synchronisation. If one process crashes the others survive, while a crashing thread can bring its whole process down.',
    hints: ['Compare memory, cost and safety.'],
    next: 'What is a deadlock, and how can you avoid one?',
  },
  {
    id: 'sd-big-o',
    roles: ['software-developer', 'backend-developer', 'frontend-developer', 'fullstack-developer', 'data-scientist'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'Explain Big O notation, and compare finding an item in an array with looking it up in a hash map.',
    anchors: 'big o|complexity|o(n)|o(1)|hash|array|time complexity',
    points: [
      { label: 'Big O describes how cost grows with input size', terms: 'grows|growth|input size|scales|worst case|upper bound|as n increases' },
      { label: 'Searching an unsorted array is O(n)', terms: 'o n|o(n)|linear|every element|each element' },
      { label: 'Hash map lookup is O(1) on average', terms: 'o 1|o(1)|constant|average' },
      { label: 'Collisions can make the worst case O(n)', terms: 'collision|worst case|degrade|bucket' },
      { label: 'Trade offs such as memory or ordering', terms: 'memory|space|order|sorted|binary search|log n' },
    ],
    model:
      'Big O describes how the time or memory an algorithm needs grows as the input grows, ignoring constants. Finding a value in an unsorted array means checking each element, so it is O(n): twice the data, roughly twice the time. A hash map hashes the key to a bucket, so a lookup is O(1) on average regardless of size. In the worst case, many keys collide in one bucket and it degrades towards O(n). The hash map also uses more memory and keeps no order, while a sorted array lets you binary search in O(log n).',
    hints: ['Define it in plain words first.', 'Then give both complexities and one caveat.'],
    next: 'What is the time complexity of inserting into a dynamic array, and why is it called amortised?',
  },
  {
    id: 'sd-code-review',
    roles: ['software-developer', 'frontend-developer', 'backend-developer', 'fullstack-developer', 'mobile-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'What do you look for when you review someone else’s code?',
    anchors: 'review|pull request|code review|pr',
    points: [
      { label: 'Correctness and edge cases', terms: 'correct|correctness|bug|logic|edge case|null|error handling' },
      { label: 'Readability and maintainability', terms: 'readab|naming|clear|clarity|maintainab|simple|complex' },
      { label: 'Tests', terms: 'test|tests|coverage' },
      { label: 'Security and performance risks', terms: 'security|injection|secret|performance|n+1|query' },
      { label: 'Tone: explain why, ask questions, separate blockers from nits', terms: 'kind|respectful|explain why|ask question|suggest|nit|blocking|tone|praise' },
    ],
    model:
      'I read the description first to understand what the change is meant to do, then check that it actually does it, including edge cases such as empty input, nulls and failures. Next I look at whether a new teammate could understand it in six months: naming, size of functions, unnecessary complexity. I check there are tests for the new behaviour and look for security or performance risks, like unvalidated input or a query inside a loop. In comments I explain why, phrase things as questions where I may be wrong, and label small style points as nits so they do not block the merge.',
    hints: ['Cover what you check and how you give the feedback.'],
    next: 'How do you handle a pull request that is 2,000 lines long?',
  },
  {
    id: 'sd-solid',
    roles: ['software-developer', 'backend-developer', 'mobile-developer', 'system-architect'],
    category: 'technical',
    levels: ['mid'],
    question: 'What are the SOLID principles? Give a practical example of at least one.',
    anchors: 'solid|single responsibility|open closed|liskov|interface segregation|dependency inversion',
    points: [
      { label: 'Single responsibility', terms: 'single responsibility|one reason to change|one job' },
      { label: 'Open and closed', terms: 'open closed|open for extension|closed for modification|extend without' },
      { label: 'Liskov substitution', terms: 'liskov|substitut|subtype|subclass' },
      { label: 'Interface segregation', terms: 'interface segregation|small interfaces|specific interface|fat interface' },
      { label: 'Dependency inversion', terms: 'dependency inversion|depend on abstraction|dependency injection|inject|interface instead' },
      { label: 'A concrete example', terms: 'example|for example|for instance|class|service|repository' },
    ],
    model:
      'SOLID is five design guidelines. Single responsibility: a class should have one reason to change. Open and closed: you extend behaviour by adding code rather than editing tested code. Liskov substitution: a subclass must be usable anywhere its parent is. Interface segregation: several small interfaces beat one large one. Dependency inversion: depend on abstractions, not concrete classes. For example, an OrderService that takes a PaymentGateway interface in its constructor, instead of creating a Stripe client itself, can be tested with a fake gateway and switched to another provider without changing the service.',
    hints: ['Name all five briefly.', 'Spend most time on one real example.'],
    next: 'When can following these principles too strictly make code worse?',
  },
  {
    id: 'sd-debug-prod',
    roles: ['software-developer', 'backend-developer', 'fullstack-developer', 'devops-engineer', 'mobile-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'A bug happens in production but you cannot reproduce it locally. How do you track it down?',
    anchors: 'bug|production|reproduce|debug|logs|issue|error',
    points: [
      { label: 'Gather evidence from logs, metrics, traces and error tracking', terms: 'log|logs|logging|metrics|trace|tracing|sentry|monitoring|observability|error tracking' },
      { label: 'Look for what differs from local: data, config, scale, timing', terms: 'data|config|environment|version|scale|timing|concurren|differ|traffic' },
      { label: 'Narrow it down: when it started, who is affected, recent changes', terms: 'when it started|recent deploy|recent change|which users|pattern|bisect|narrow|isolate' },
      { label: 'Reduce impact first if users are hurting', terms: 'mitigat|rollback|roll back|feature flag|hotfix|workaround' },
      { label: 'Add logging if needed and write a regression test once fixed', terms: 'add logging|more logging|instrument|regression test|test|postmortem' },
    ],
    model:
      'First I limit the damage: if it is serious and started after a deploy, I roll back or turn off the feature flag. Then I gather evidence: error tracking for the stack trace, logs and traces around the failing requests, and metrics to see when it started and who is affected. I compare those requests with what I do locally, because the difference is usually data, configuration, scale or timing, such as a race that only appears under load. If the evidence is not enough, I add targeted logging and wait for the next occurrence. Once fixed, I add a regression test.',
    hints: ['Think: limit impact, gather evidence, find the difference, fix, prevent.'],
    next: 'What would you log to catch a race condition that only happens under load?',
  },
  {
    id: 'sd-git-rebase',
    roles: ['software-developer', 'frontend-developer', 'backend-developer', 'fullstack-developer', 'mobile-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is the difference between git merge and git rebase, and when would you use each?',
    anchors: 'merge|rebase|git|branch|commit',
    points: [
      { label: 'Merge keeps history and adds a merge commit', terms: 'merge commit|keeps history|preserve|non linear|history as it happened' },
      { label: 'Rebase replays commits to make a linear history', terms: 'replay|reapply|rewrite|linear|on top of|new commits' },
      { label: 'Do not rebase shared branches', terms: 'shared branch|public branch|never rebase|force push|others have pulled|golden rule' },
      { label: 'Conflicts happen in both', terms: 'conflict|conflicts' },
      { label: 'A practical rule for when to use which', terms: 'i use|i rebase|i merge|in practice|before opening|update my branch|stay up to date|squash|team convention|my own branch|feature branch' },
    ],
    model:
      'Merge combines two branches by creating a merge commit, keeping the history exactly as it happened. Rebase takes my commits and replays them on top of another branch, creating new commits and a straight, linear history. Because rebase rewrites commits, I never rebase a branch others have pulled, as it forces them to deal with rewritten history. In practice I rebase my own feature branch onto main to stay up to date and keep it tidy, then merge it into main through a pull request. Either way conflicts can happen; with rebase I resolve them commit by commit.',
    hints: ['Explain what each does to history.', 'Give the rule about shared branches.'],
    next: 'You rebased and force pushed a shared branch by mistake. How do you recover?',
  },

  // ---------------------------------------------------------------- DevOps
  {
    id: 'do-cicd',
    roles: ['devops-engineer', 'software-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How would you design a CI/CD pipeline for a web service?',
    anchors: 'ci|cd|pipeline|build|deploy|continuous',
    points: [
      { label: 'Build, lint and test on every change', terms: 'build|lint|test|every commit|pull request|on push' },
      { label: 'Produce one versioned artifact and reuse it', terms: 'artifact|image|docker|registry|version|tag|build once' },
      { label: 'Promote through environments', terms: 'staging|production|environment|promote|preview' },
      { label: 'A safe deployment strategy', terms: 'blue green|canary|rolling|gradual|percentage' },
      { label: 'Automatic or quick rollback', terms: 'rollback|roll back|revert|previous version' },
      { label: 'Secrets handled securely', terms: 'secret|vault|credentials|environment variable|kms' },
    ],
    model:
      'On every pull request the pipeline installs dependencies, lints, runs unit and integration tests and builds a Docker image. On merge to main it builds that image once, tags it with the commit hash and pushes it to a registry, so the exact same artifact goes to every environment. It deploys to staging, runs smoke tests, then rolls out to production as a canary to a small share of traffic while watching error rates, before going to 100 percent. Rollback means redeploying the previous image tag. Secrets come from a vault or the cloud secret manager, never from the repository.',
    hints: ['Walk from pull request to production.', 'Mention artifacts, environments, rollout and rollback.'],
    next: 'How would you speed up a pipeline that now takes 40 minutes?',
  },
  {
    id: 'do-k8s-basics',
    roles: ['devops-engineer', 'system-architect', 'backend-developer'],
    category: 'technical',
    levels: ['mid'],
    question: 'In Kubernetes, what are a Pod, a Deployment and a Service, and how do they work together?',
    anchors: 'kubernetes|k8s|pod|deployment|service',
    points: [
      { label: 'A Pod is the smallest unit, one or more containers', terms: 'pod|smallest|container|containers' },
      { label: 'A Deployment keeps the desired number of Pods running and handles rollouts', terms: 'deployment|replica|replicaset|desired state|self heal|restarts|rolling update|rollout' },
      { label: 'A Service gives Pods a stable address and load balances', terms: 'service|stable|ip|dns name|load balanc|selector|label|clusterip' },
      { label: 'External traffic through an Ingress or load balancer', terms: 'ingress|load balancer|nodeport|external' },
      { label: 'Configuration through ConfigMaps and Secrets', terms: 'configmap|secret|environment' },
    ],
    model:
      'A Pod is the smallest deployable unit: one or more containers that share a network address. Pods are temporary and can be replaced at any time. A Deployment describes the desired state, for example three replicas of version 2 of my image, and Kubernetes keeps that many Pods running, replaces failed ones and performs rolling updates. Because Pod IPs change, a Service gives a stable DNS name and load balances across all Pods that match its label selector. For traffic from outside the cluster I add an Ingress, and configuration comes from ConfigMaps and Secrets.',
    hints: ['Explain each object and how they connect through labels.'],
    next: 'A Pod keeps restarting with CrashLoopBackOff. How do you investigate?',
  },
  {
    id: 'do-monitoring',
    roles: ['devops-engineer', 'system-architect', 'backend-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'What would you monitor and alert on for a production web service?',
    anchors: 'monitor|alert|metric|observability|logging|dashboard',
    points: [
      { label: 'The golden signals: latency, traffic, errors, saturation', terms: 'latency|traffic|error rate|errors|saturation|golden signals|red method|use method' },
      { label: 'Metrics, logs and traces together', terms: 'metrics|logs|logging|traces|tracing|opentelemetry' },
      { label: 'Service level objectives and error budgets', terms: 'slo|sli|error budget|service level' },
      { label: 'Alert on user facing symptoms, keep alerts actionable', terms: 'symptom|actionable|page|on call|alert fatigue|noise|runbook' },
      { label: 'Tools and dashboards', terms: 'prometheus|grafana|datadog|new relic|cloudwatch|dashboard' },
    ],
    model:
      'I start with the four golden signals for each service: request rate, error rate, latency at the 95th and 99th percentile, and saturation such as CPU, memory and queue depth. Metrics go to Prometheus and Grafana, logs are structured and searchable, and traces connect a request across services. I define SLOs, for example 99.9 percent of requests succeed in under 300 ms, and page someone only when the error budget is burning fast, because that reflects user pain. Everything else becomes a ticket or dashboard, and every page links to a runbook.',
    hints: ['Name what to measure, then explain how you decide what wakes someone up.'],
    next: 'Your team gets 30 alerts a night. How do you fix that?',
  },
  {
    id: 'do-iac',
    roles: ['devops-engineer', 'system-architect'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is infrastructure as code, and how do you work with it safely in a team?',
    anchors: 'infrastructure as code|iac|terraform|cloudformation|pulumi|ansible',
    points: [
      { label: 'Infrastructure defined in version controlled files', terms: 'version control|git|code|declarative|files|repository' },
      { label: 'Repeatable, consistent environments', terms: 'repeatab|reproducib|consistent|same environment|recreate|drift' },
      { label: 'Named tools', terms: 'terraform|cloudformation|pulumi|ansible|cdk|bicep' },
      { label: 'Remote state with locking', terms: 'state|state file|remote state|lock|backend' },
      { label: 'Plan, review, then apply', terms: 'plan|review|pull request|apply|approval' },
    ],
    model:
      'Infrastructure as code means servers, networks and databases are described in files, usually with Terraform, and stored in Git like application code. That makes environments repeatable, so staging matches production, and every change has history and review. In a team, Terraform state lives in a remote backend with locking, so two people cannot apply at once. Every change goes through a pull request where CI runs terraform plan and posts the diff, someone reviews exactly what will change, and only then is it applied, ideally by the pipeline rather than a laptop.',
    hints: ['Explain the benefit, then the team workflow.'],
    next: 'Someone changed a resource by hand in the console. How do you detect and fix the drift?',
  },
  {
    id: 'do-incident',
    roles: ['devops-engineer', 'backend-developer', 'system-architect', 'engineering-manager'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'You are on call and the site goes down at 2 AM. Walk me through what you do.',
    anchors: 'down|outage|incident|on call|alert|site',
    points: [
      { label: 'Acknowledge and judge severity', terms: 'acknowledge|severity|triage|assess|incident commander|declare' },
      { label: 'Communicate early through a status page or channel', terms: 'status page|communicat|stakeholder|update|channel|inform' },
      { label: 'Restore service first: rollback, failover, scale', terms: 'mitigat|rollback|roll back|failover|restore|restart|scale|feature flag' },
      { label: 'Use recent changes and dashboards to find the cause', terms: 'recent deploy|recent change|dashboard|logs|metrics|what changed' },
      { label: 'Blameless postmortem with action items', terms: 'postmortem|post mortem|blameless|root cause|action item|follow up' },
    ],
    model:
      'I acknowledge the page so others know someone is on it, check the dashboards to confirm the impact and declare an incident with a severity. I post in the incident channel and update the status page, even if all I can say is that we are investigating. My first goal is to restore service, not to understand it: if there was a deploy in the last hour I roll it back, otherwise I check dependencies, failover or scale up. I pull in help early if I am stuck. Once stable, I write a blameless postmortem with a timeline, root cause and owners for the follow up actions.',
    hints: ['Order matters: acknowledge, communicate, mitigate, diagnose, learn.'],
    next: 'How do you run a postmortem that does not turn into blaming someone?',
  },
  {
    id: 'do-zero-downtime',
    roles: ['devops-engineer', 'system-architect'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Compare rolling, blue green and canary deployments. How do you get zero downtime?',
    anchors: 'rolling|blue green|canary|deploy|deployment|downtime',
    points: [
      { label: 'Rolling: replace instances gradually', terms: 'rolling|gradually|one at a time|batch|instances' },
      { label: 'Blue green: switch traffic between two full environments', terms: 'blue green|two environments|switch traffic|swap|idle environment' },
      { label: 'Canary: send a small share of traffic to the new version first', terms: 'canary|small percentage|small share|5 percent|subset|gradual traffic' },
      { label: 'Health checks and draining connections', terms: 'health check|readiness|liveness|drain|graceful shutdown' },
      { label: 'Fast rollback and compatible database changes', terms: 'rollback|roll back|backward compatible|backwards compatible|migration|schema' },
    ],
    model:
      'A rolling deploy replaces instances a few at a time, which is cheap but means two versions run side by side for a while. Blue green keeps two full environments and flips traffic from blue to green at once, which gives an instant rollback but costs double capacity during the switch. A canary sends a small share, say 5 percent, to the new version and watches error rates before increasing it, which limits the blast radius. In all cases zero downtime needs readiness checks, graceful draining of open connections and database changes that both versions can work with.',
    hints: ['Explain each strategy and one trade off for each.'],
    next: 'Which metrics would you use to automatically stop a bad canary?',
  },

  // ---------------------------------------------------------------- Mobile
  {
    id: 'mo-lifecycle',
    roles: ['mobile-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'Explain the app lifecycle on iOS or Android, and how you preserve the user’s state.',
    anchors: 'lifecycle|foreground|background|activity|oncreate|onpause|scenedelegate|state',
    points: [
      { label: 'Named the lifecycle states or callbacks', terms: 'foreground|background|suspended|paused|stopped|resumed|oncreate|onresume|onpause|onstop|scenedelegate|active|inactive' },
      { label: 'Save state before the app can be killed', terms: 'save state|persist|onsaveinstancestate|savedstatehandle|restoration|state restoration|viewmodel' },
      { label: 'The system can kill a backgrounded app at any time', terms: 'killed|process death|terminated|memory pressure|reclaim' },
      { label: 'Pause expensive work in the background', terms: 'release|pause|battery|stop updates|stop location|cancel|resources' },
    ],
    model:
      'On Android an activity moves through onCreate, onStart, onResume while visible, then onPause and onStop when the user leaves. On iOS the scene becomes active, inactive and then backgrounded. The key point is that once in the background, the system can kill the process at any time to free memory, without another callback. So I keep UI state in a ViewModel with SavedStateHandle on Android, or use state restoration on iOS, and persist anything important, such as a draft, to disk when the app is paused. I also stop location updates and timers in the background to save battery.',
    hints: ['Name the states, then explain what you save and when.'],
    next: 'How would you test that your app survives process death correctly?',
  },
  {
    id: 'mo-offline',
    roles: ['mobile-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How would you make a mobile app work offline and sync when the connection comes back?',
    anchors: 'offline|sync|connection|network|local',
    points: [
      { label: 'A local database as the source of truth for the UI', terms: 'sqlite|room|core data|realm|local database|local storage|cache|source of truth' },
      { label: 'Queue changes made offline and retry', terms: 'queue|outbox|pending|retry|background sync|workmanager' },
      { label: 'Resolve conflicts with the server', terms: 'conflict|last write wins|version|timestamp|merge|crdt' },
      { label: 'Detect connectivity changes', terms: 'connectivity|network status|reachability|online|offline' },
      { label: 'Show the user what is pending', terms: 'indicator|pending|synced|banner|optimistic|status' },
    ],
    model:
      'I would make a local database such as Room or SQLite the source of truth: the UI always reads from it, and the network only updates it. When the user changes something offline, the change is written locally and added to an outbox queue. A background job, such as WorkManager on Android, sends queued changes when connectivity returns and retries with backoff. Each record carries a version, so the server can detect conflicts; for simple data last write wins is fine, for important data I show the conflict. The UI marks items that are not synced yet.',
    hints: ['Explain where data lives, how changes are queued, and conflicts.'],
    next: 'Two devices edit the same note offline. What happens when both come online?',
  },
  {
    id: 'mo-performance',
    roles: ['mobile-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'A long list in your app scrolls with visible stutter. How do you find and fix the problem?',
    anchors: 'scroll|jank|stutter|list|frame|performance',
    points: [
      { label: 'Profile instead of guessing', terms: 'profiler|instruments|systrace|perfetto|android studio|time profiler|frame|fps' },
      { label: 'Keep heavy work off the main thread', terms: 'main thread|ui thread|background thread|off the main|coroutine|async' },
      { label: 'Recycle cells and avoid rebuilding them', terms: 'recycler|recyclerview|reuse|cell reuse|lazycolumn|flatlist|diffutil|lazy' },
      { label: 'Decode and resize images properly', terms: 'image|decode|resize|thumbnail|glide|coil|cache' },
      { label: 'Simplify layouts', terms: 'overdraw|layout|nested|hierarchy|measure|flatten' },
    ],
    model:
      'I start by profiling on a real mid range device with Android Studio or Instruments to see which frames miss the 16 ms budget and what the main thread is doing. Common causes are decoding full size images on the main thread, deep nested layouts that are expensive to measure, and work done while binding each row. Fixes are loading and resizing images in the background with a library such as Coil or Glide, flattening the layout, reusing cells properly with DiffUtil so only changed rows rebind, and moving formatting or parsing off the main thread.',
    hints: ['Measure first, then go through main thread work, images and layout.'],
    next: 'How would you catch a performance regression like this before release?',
  },
  {
    id: 'mo-native-cross',
    roles: ['mobile-developer'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'When would you choose native development over a cross platform framework such as React Native or Flutter?',
    anchors: 'native|cross platform|react native|flutter|swift|kotlin',
    points: [
      { label: 'Code sharing and team speed with cross platform', terms: 'share code|one codebase|single codebase|faster|team|cost' },
      { label: 'Performance and smoothness', terms: 'performance|smooth|animation|heavy|graphics' },
      { label: 'Access to new platform features and APIs', terms: 'platform api|native api|new features|bluetooth|camera|ar|widget|bridge' },
      { label: 'Team skills and ecosystem', terms: 'team skill|javascript|dart|ecosystem|libraries|hiring' },
      { label: 'A clear decision rule', terms: 'i would choose|choose native|choose flutter|choose react native|depends|if the app' },
    ],
    model:
      'Cross platform frameworks let one team ship iOS and Android from mostly one codebase, which is a big win for content and form based apps and for teams that already know JavaScript or Dart. I would choose native when the app depends heavily on platform features, such as advanced camera work, Bluetooth, widgets or the newest OS APIs, or when it needs demanding animations and graphics where every frame matters. A middle path is cross platform for most screens with native modules for the few hard parts.',
    hints: ['Compare on speed of delivery, performance and platform access.'],
    next: 'How would you structure a project that mixes Flutter screens with native modules?',
  },
  {
    id: 'mo-secure-storage',
    roles: ['mobile-developer'],
    category: 'technical',
    levels: ['mid'],
    question: 'How do you store an authentication token securely in a mobile app?',
    anchors: 'token|store|secure|keychain|keystore|storage',
    points: [
      { label: 'Use the Keychain on iOS and Keystore backed storage on Android', terms: 'keychain|keystore|encryptedsharedpreferences|secure storage|secure enclave' },
      { label: 'Avoid plain storage', terms: 'shared preferences|userdefaults|plain text|asyncstorage|not in|never store' },
      { label: 'Short lived tokens with refresh', terms: 'expire|short lived|refresh token|rotation|revoke' },
      { label: 'HTTPS and certificate pinning', terms: 'https|tls|pinning|certificate' },
      { label: 'Optional biometric protection', terms: 'biometric|face id|touch id|fingerprint' },
    ],
    model:
      'I never put tokens in UserDefaults, SharedPreferences or AsyncStorage, because those are plain files. On iOS the token goes in the Keychain, and on Android in storage encrypted with a key from the Android Keystore, for example EncryptedSharedPreferences. Access tokens are short lived and refreshed with a refresh token that the server can revoke. All traffic is HTTPS, with certificate pinning for sensitive apps, and for banking style apps I gate access to the refresh token behind biometrics.',
    hints: ['Say where it goes on each platform and what to avoid.'],
    next: 'A rooted device can read app memory. What else can you do on the server side?',
  },

  // -------------------------------------------------------------------- QA
  {
    id: 'qa-bug-report',
    roles: ['qa-engineer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What makes a good bug report?',
    anchors: 'bug report|bug|report|reproduce|ticket',
    points: [
      { label: 'Clear title and exact steps to reproduce', terms: 'steps to reproduce|steps|reproduce|repro|title' },
      { label: 'Expected versus actual result', terms: 'expected|actual' },
      { label: 'Environment details', terms: 'environment|browser|device|os|version|build|staging' },
      { label: 'Severity and priority', terms: 'severity|priority|impact' },
      { label: 'Evidence such as screenshots, video or logs', terms: 'screenshot|video|recording|log|logs|console|har' },
    ],
    model:
      'A good bug report lets a developer reproduce the problem without asking a single question. It has a specific title, such as "Checkout total ignores discount code on Safari 17", numbered steps to reproduce from a clean state, the expected result and the actual result. It lists the environment: build or version, browser or device, OS and account type. It includes evidence, such as a screenshot or short video and console or network logs. Finally it gives a severity based on impact and, if known, how often it happens.',
    hints: ['Think about what the developer needs to reproduce it.'],
    next: 'A developer marks your bug as cannot reproduce. What do you do next?',
  },
  {
    id: 'qa-login-tests',
    roles: ['qa-engineer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'How would you test a login page?',
    anchors: 'login|password|sign in|username|email',
    points: [
      { label: 'Positive cases', terms: 'valid credentials|correct password|successful login|happy path|valid' },
      { label: 'Negative cases', terms: 'invalid|wrong password|incorrect|empty|blank|unregistered|error message' },
      { label: 'Edge cases and security', terms: 'sql injection|xss|lockout|brute force|rate limit|max length|special character|case sensitive|https' },
      { label: 'Session behaviour', terms: 'session|remember me|logout|timeout|cookie|back button' },
      { label: 'Usability, accessibility and devices', terms: 'accessib|keyboard|screen reader|mobile|browser|responsive|password manager' },
      { label: 'What to automate', terms: 'automat|regression|selenium|playwright|cypress' },
    ],
    model:
      'I start with positive cases: valid email and password log in and land on the right page. Then negative cases: wrong password, unknown email, empty fields, with clear but not revealing error messages. Then edge and security cases: very long input, special characters, SQL injection and script strings, password case sensitivity, account lockout or rate limiting after repeated failures, and that the form only works over HTTPS. I test session behaviour such as remember me, logout and expiry, check keyboard and screen reader use, and run it on the main browsers and mobile. The stable core cases go into the automated regression suite.',
    hints: ['Group your answer: positive, negative, security, session, usability.'],
    next: 'Which three of these would you automate first, and why?',
  },
  {
    id: 'qa-automate-what',
    roles: ['qa-engineer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How do you decide which tests to automate and which to keep manual?',
    anchors: 'automat|manual|test',
    points: [
      { label: 'Automate repetitive, stable, high value checks such as regression', terms: 'repetitive|regression|stable|frequently|every release|critical path|smoke' },
      { label: 'Keep exploratory and usability testing manual', terms: 'exploratory|usability|look and feel|one off|manual|human judgement' },
      { label: 'Consider the cost and return of automating', terms: 'roi|return|cost|maintenance|effort|value' },
      { label: 'Prefer lower level tests when possible', terms: 'pyramid|unit|api|lower level|ui tests are slow' },
      { label: 'Avoid flaky or constantly changing areas', terms: 'flaky|changing|unstable|still changing' },
    ],
    model:
      'I automate checks that are repeated every release, stable and costly to miss: login, checkout and other critical paths, plus the regression suite. I push them as low as possible, preferring API tests to UI tests because they are faster and less flaky. I keep exploratory testing, usability and visual judgement manual, along with features that are still changing every week, because maintaining their automation would cost more than it saves. The rough test is: will this run many times, and will the result stay meaningful?',
    hints: ['Give criteria, not just examples.'],
    next: 'Your UI test suite takes two hours. How would you cut it down?',
  },
  {
    id: 'qa-flaky',
    roles: ['qa-engineer', 'software-developer', 'fullstack-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How do you deal with flaky automated tests?',
    anchors: 'flaky|flakiness|intermittent|random|fails sometimes',
    points: [
      { label: 'Track and quarantine them instead of ignoring failures', terms: 'quarantine|track|label|separate|do not ignore|dashboard|rerun data' },
      { label: 'Common causes: timing, shared state, order, external services', terms: 'timing|sleep|wait|race|shared state|order|test data|network|external service|animation' },
      { label: 'Fix with explicit waits, isolation and controlled data', terms: 'explicit wait|wait for|await|isolat|independent|mock|stub|seed|fresh data' },
      { label: 'Find the cause by reproducing under the same conditions', terms: 'reproduce|repeat|loop|run many times|logs|video|trace' },
      { label: 'Fix or delete within a set time', terms: 'fix or delete|delete|owner|deadline|within' },
    ],
    model:
      'A flaky test is worse than no test because people learn to ignore red builds. I first move it to a quarantine suite so it stops blocking merges, and record it with an owner and a deadline. Then I reproduce it by running it in a loop with traces or video. The usual causes are fixed sleeps instead of waiting for a real condition, tests sharing data or depending on run order, and calls to real external services. The fixes are explicit waits on state, each test creating its own data, and mocking external services. If it is not fixed by the deadline, it is deleted and the gap is covered another way.',
    hints: ['Explain what you do immediately, then how you fix the cause.'],
    next: 'How would you measure flakiness across the whole suite?',
  },
  {
    id: 'qa-severity-priority',
    roles: ['qa-engineer', 'product-manager'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is the difference between bug severity and bug priority? Give an example where they differ.',
    anchors: 'severity|priority',
    points: [
      { label: 'Severity is the impact on the system or user', terms: 'impact|how bad|technical|effect|damage' },
      { label: 'Priority is how soon it should be fixed', terms: 'urgency|how soon|when to fix|order|business' },
      { label: 'Example: high severity but low priority', terms: 'high severity low priority|rarely used|crash in an old|edge case|few users' },
      { label: 'Example: low severity but high priority', terms: 'low severity high priority|typo|logo|homepage|brand|company name' },
    ],
    model:
      'Severity is how much damage the bug does, while priority is how soon the business needs it fixed. Usually they move together, but not always. A crash in a rarely used admin export that one internal person uses twice a year is high severity but low priority. A typo in the company name on the homepage is low severity, since nothing breaks, but high priority, because every visitor sees it. QA usually sets severity, and priority is agreed with the product owner.',
    hints: ['Define both, then give one example of each mismatch.'],
    next: 'Who should decide priority, and what if you disagree?',
  },

  // ------------------------------------------------------- System architect
  {
    id: 'ar-monolith-micro',
    roles: ['system-architect', 'backend-developer', 'engineering-manager'],
    category: 'technical',
    levels: ['senior', 'mid'],
    question: 'When would you choose microservices over a monolith, and what are the costs?',
    anchors: 'microservice|monolith|services',
    points: [
      { label: 'Team size and ownership drive the decision', terms: 'team|teams|ownership|organisation|organization|conway' },
      { label: 'Independent deployment and scaling', terms: 'independent|deploy separately|scale separately|scale independently|release' },
      { label: 'Operational complexity: network, monitoring, debugging', terms: 'complex|operational|network|latency|monitoring|tracing|debugging|devops' },
      { label: 'Data consistency across services', terms: 'consistency|distributed transaction|saga|eventual|data ownership|shared database' },
      { label: 'Start with a modular monolith', terms: 'modular monolith|start with a monolith|start simple|split later|well structured' },
    ],
    model:
      'Microservices mainly solve an organisational problem: many teams wanting to deploy and scale their parts independently. The cost is real: network calls fail and add latency, you need tracing and good monitoring, and data that used to be one transaction now needs sagas and eventual consistency. For most products I would start with a modular monolith, with clear module boundaries and no shared tables across modules, and split out a service only when a team or a scaling need clearly justifies it, for example a payment component with different release and compliance needs.',
    hints: ['Tie the answer to team size and operational cost.'],
    next: 'How would you split the first service out of an existing monolith safely?',
  },
  {
    id: 'ar-cap',
    roles: ['system-architect', 'backend-developer'],
    category: 'technical',
    levels: ['senior'],
    question: 'Explain the CAP theorem and how it affects real design decisions.',
    anchors: 'cap|consistency|availability|partition',
    points: [
      { label: 'Defined consistency, availability and partition tolerance', terms: 'consistency|availability|partition tolerance|partition' },
      { label: 'Partitions will happen, so the real choice is C or A during one', terms: 'partitions happen|network partition|must tolerate|choose between|during a partition' },
      { label: 'Gave CP and AP examples', terms: 'cp|ap|bank|payment|shopping cart|social feed|likes|zookeeper|cassandra|dynamo' },
      { label: 'Mentioned latency and PACELC, or tunable consistency', terms: 'pacelc|latency|tunable|quorum|eventual consistency' },
      { label: 'The choice can differ per feature', terms: 'per feature|per use case|different parts|depends on the data|each feature' },
    ],
    model:
      'CAP says that when a network partition splits a distributed system, you must choose between consistency, where every read sees the latest write, and availability, where every request gets an answer. Partitions will happen, so the practical question is what each feature should do during one. An account balance should refuse writes rather than show wrong data, so it is CP. A like counter or shopping cart can accept writes on both sides and reconcile later, so it is AP. PACELC adds that even without partitions you trade latency against consistency, which is why systems like Cassandra offer tunable quorums.',
    hints: ['Define it, then show you would choose per feature.'],
    next: 'How would you design the checkout so it stays available without overselling stock?',
  },
  {
    id: 'ar-event-driven',
    roles: ['system-architect', 'backend-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'What are the benefits and the risks of an event driven architecture?',
    anchors: 'event|events|queue|broker|kafka|message|publish|subscribe',
    points: [
      { label: 'Decouples producers and consumers', terms: 'decoupl|loosely coupled|independent|do not know about|publish|subscribe' },
      { label: 'Named a broker or queue', terms: 'kafka|rabbitmq|sqs|sns|pub sub|pubsub|broker|queue|event bus' },
      { label: 'Eventual consistency', terms: 'eventual|eventually consistent|consistency|delay|lag' },
      { label: 'Duplicates and ordering mean consumers must be idempotent', terms: 'idempot|duplicate|at least once|ordering|order|exactly once|dedup' },
      { label: 'Harder to debug and observe', terms: 'debug|trace|tracing|observab|correlation id|dead letter|monitor' },
    ],
    model:
      'Events let a service announce that something happened, such as OrderPlaced, without knowing who listens, so new consumers like email or analytics can be added without touching the order service, and spikes are absorbed by the queue. Brokers such as Kafka or SQS usually deliver at least once, so consumers must be idempotent and handle duplicates, and ordering is only guaranteed within a partition. The system becomes eventually consistent, which users may notice. It is also harder to debug, so you need correlation IDs, tracing across consumers and dead letter queues for messages that keep failing.',
    hints: ['Give benefits, then the three main risks.'],
    next: 'How would you guarantee an event is published only if the database write succeeded?',
  },
  {
    id: 'ar-high-availability',
    roles: ['system-architect', 'devops-engineer'],
    category: 'technical',
    levels: ['senior'],
    question: 'How do you design a system for high availability?',
    anchors: 'availability|uptime|redundan|failover|resilien',
    points: [
      { label: 'Remove single points of failure with redundancy', terms: 'single point of failure|redundan|multiple instances|replica|replicas' },
      { label: 'Spread across availability zones or regions', terms: 'availability zone|multi az|multi region|zones|region' },
      { label: 'Health checks and automatic failover', terms: 'health check|failover|automatic|load balancer|leader election' },
      { label: 'Graceful degradation, timeouts and circuit breakers', terms: 'graceful degradation|degrade|circuit breaker|timeout|retry|bulkhead|fallback' },
      { label: 'Backups and recovery targets', terms: 'backup|disaster recovery|rto|rpo|restore|test the restore' },
      { label: 'Define the target and test failure', terms: 'slo|99 9|nines|target|chaos|game day|test failover' },
    ],
    model:
      'I start from the target, for example 99.95 percent, because each extra nine changes the cost. Then I remove single points of failure: several stateless instances behind a load balancer across at least two availability zones, and a replicated database with automatic failover. Calls to dependencies get timeouts, limited retries and circuit breakers, so one slow service does not take everything down, and non essential features degrade gracefully. Backups have defined RPO and RTO and are restored regularly to prove they work. Finally I test failover on purpose, with game days, rather than trusting the diagram.',
    hints: ['Start from a target, then go layer by layer.'],
    next: 'What changes if the requirement becomes surviving the loss of a whole region?',
  },
  {
    id: 'ar-api-versioning',
    roles: ['system-architect', 'backend-developer'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How do you evolve a public API without breaking existing clients?',
    anchors: 'api|version|versioning|breaking|backward|compatib|client',
    points: [
      { label: 'Prefer additive, backward compatible changes', terms: 'additive|add fields|optional|backward compatible|backwards compatible|non breaking' },
      { label: 'A versioning strategy for breaking changes', terms: 'version|v1|v2|url version|header|media type|date based' },
      { label: 'Deprecation policy with a timeline', terms: 'deprecat|sunset|timeline|notice|months|end of life' },
      { label: 'Contract tests or schema checks', terms: 'contract test|schema|openapi|consumer driven|pact|compatibility check' },
      { label: 'Communicate and measure who still uses old versions', terms: 'communicat|changelog|email|usage|metrics|who still' },
    ],
    model:
      'Most changes should be additive: new optional fields and new endpoints never break clients, provided clients ignore unknown fields. For genuinely breaking changes I introduce a new version, for example /v2 or a dated version header, and run both side by side. The old version gets a published deprecation date, a Sunset header and an announcement in the changelog and by email, and I track usage per client so I can contact whoever is still on it. An OpenAPI schema with automated compatibility checks in CI stops anyone shipping a breaking change by accident.',
    hints: ['Cover non breaking changes first, then how you handle breaking ones.'],
    next: 'A large customer refuses to move off v1. What do you do?',
  },
];
