import type { BankQuestion } from './bank-types';

// Technical round for data, product and management roles. For product managers
// this round is product sense, and for engineering managers it is leadership.

export const TECHNICAL_OTHER: BankQuestion[] = [
  // ----------------------------------------------------------- Data scientist
  {
    id: 'ds-bias-variance',
    roles: ['data-scientist'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'Explain the bias variance tradeoff. How do you tell which problem a model has?',
    anchors: 'bias|variance|tradeoff|trade off|underfit|overfit|model',
    points: [
      { label: 'Bias means the model is too simple and underfits', terms: 'underfit|underfitting|too simple|high bias|misses the pattern|cannot capture|wrong assumptions' },
      { label: 'Variance means the model is too sensitive and overfits', terms: 'overfit|overfitting|high variance|memorize|memorise|noise|too complex|sensitive to the training data' },
      { label: 'Diagnose by comparing training and validation error', terms: 'training error|validation error|test error|train and validation|learning curve|gap between|cross validation|holdout' },
      { label: 'Fixes for each side', terms: 'regularization|regularisation|more data|simpler model|more features|more complex model|dropout|pruning|early stopping|ensemble|bagging' },
    ],
    model:
      'Bias is error from a model that is too simple to capture the real pattern, so it underfits and does badly on both training and validation data. Variance is error from a model that fits the training data too closely, including its noise, so training error is low but validation error is much higher. I diagnose it by comparing the two errors or plotting learning curves. If both are high, I add features or try a more flexible model. If there is a big gap, I add data, regularize, simplify the model, or use bagging. Lowering one usually raises the other, so the goal is the point with the lowest validation error.',
    hints: ['Define both terms in plain words.', 'Say exactly how you would diagnose it and what you would change.'],
    next: 'How does regularization strength affect bias and variance in a linear model?',
  },
  {
    id: 'ds-imbalanced',
    roles: ['data-scientist'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'You are building a fraud model and only 0.5 percent of transactions are fraud. How do you handle the class imbalance?',
    anchors: 'imbalance|imbalanced|fraud|minority|class|rare',
    points: [
      { label: 'Accuracy is misleading, use better metrics', terms: 'accuracy is misleading|accuracy|precision|recall|f1|pr auc|precision recall curve|auprc|roc' },
      { label: 'Resampling such as undersampling or oversampling', terms: 'undersample|undersampling|oversample|oversampling|smote|resample|resampling|downsample' },
      { label: 'Class weights or cost sensitive learning', terms: 'class weight|class weights|weighted loss|cost sensitive|penalize|scale pos weight|cost of a false negative' },
      { label: 'Tune the decision threshold to the business cost', terms: 'threshold|cut off|cutoff|operating point|business cost|cost of fraud|cost of review' },
      { label: 'Validate correctly, for example stratified or time based splits', terms: 'stratified|time based split|time split|out of time|leakage|resample only the training|after the split' },
    ],
    model:
      'First I stop looking at accuracy, because predicting no fraud every time would score 99.5 percent. I use precision, recall and the precision recall curve instead. Then I try class weights in the loss, since that is cheap and does not change the data, and compare with undersampling the majority or SMOTE, applied only to the training fold. Fraud data changes over time, so I validate on a later time period rather than a random split. Finally I pick the decision threshold from the real costs: a missed fraud might cost the full transaction, while a false alarm costs a manual review, so the threshold should balance those two.',
    hints: ['Say why accuracy fails here.', 'Cover data, model and threshold choices.'],
    next: 'How would you explain the chosen threshold to the fraud operations team?',
  },
  {
    id: 'ds-missing-data',
    roles: ['data-scientist', 'data-analyst'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'How do you handle missing values in a dataset before training a model?',
    anchors: 'missing|null|nan|impute|imputation|empty',
    points: [
      { label: 'Understand why it is missing first', terms: 'why it is missing|why the data is missing|random|mcar|mar|mnar|missing at random|pattern|investigate' },
      { label: 'Drop rows or columns only when it is safe', terms: 'drop|remove rows|delete rows|drop the column|small percentage|few rows' },
      { label: 'Impute with a sensible method', terms: 'impute|imputation|mean|median|mode|most frequent|knn|model based|forward fill|interpolate' },
      { label: 'Keep the signal with a missing flag', terms: 'indicator|flag|is missing|missing column|binary column|missingness as a feature' },
      { label: 'Fit imputation on training data only', terms: 'training data only|fit on train|pipeline|leakage|same transform|test set' },
    ],
    model:
      'I start by checking how much is missing and why. If a field is blank because the customer never had that product, the blank itself means something. If less than a few percent of rows are missing at random, dropping them can be fine. Otherwise I impute: median for skewed numbers, the most frequent value for categories, and a model based method like KNN when the field matters a lot. I usually add a flag column that says the value was missing, so the model can still use that signal. The imputer is fitted on the training data only and applied to test data inside a pipeline, so nothing leaks.',
    hints: ['Start with why the data is missing.', 'Name at least two methods and when you would use each.'],
    next: 'When would dropping rows with missing values bias your model?',
  },
  {
    id: 'ds-precision-recall',
    roles: ['data-scientist'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'What is the difference between precision and recall, and when would you favour one over the other?',
    anchors: 'precision|recall|false positive|false negative',
    points: [
      { label: 'Precision: of the predicted positives, how many were right', terms: 'precision|predicted positive|of the ones flagged|of the predictions|false positive|tp over tp plus fp' },
      { label: 'Recall: of the real positives, how many were found', terms: 'recall|sensitivity|actual positive|real positives|false negative|tp over tp plus fn|how many we caught' },
      { label: 'They trade off through the threshold', terms: 'tradeoff|trade off|threshold|raise the threshold|lower the threshold|f1|balance' },
      { label: 'A real example for each side', terms: 'cancer|disease|medical|screening|spam|fraud|search|recommend|legal|email' },
    ],
    model:
      'Precision asks: of everything the model flagged as positive, how much was really positive. Recall asks: of all the real positives, how many did the model find. Moving the threshold trades one for the other. I favour recall when missing a case is expensive, such as screening for a disease, where a false alarm just means another test. I favour precision when false alarms hurt, such as a spam filter, where sending a real email to spam is worse than letting one spam message through. When both matter, I look at F1 or the full precision recall curve.',
    hints: ['Define each with false positives and false negatives.', 'Give one example where each one matters more.'],
    next: 'How would you choose a threshold if the business gave you a cost for each error type?',
  },
  {
    id: 'ds-leakage',
    roles: ['data-scientist'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Your model scores very well offline but performs badly in production. What could be going wrong?',
    anchors: 'offline|production|performs badly|model|validation|deploy',
    points: [
      { label: 'Data leakage from future or target information', terms: 'leakage|leak|future data|target leakage|information from the future|label leak' },
      { label: 'Training and serving skew', terms: 'training serving skew|serving skew|feature pipeline|different code|different preprocessing|feature store' },
      { label: 'Distribution or concept drift', terms: 'drift|data drift|concept drift|distribution shift|changed behaviour|changed behavior|seasonality' },
      { label: 'Wrong validation split', terms: 'random split|time split|time based|group split|same user in train and test|validation split' },
      { label: 'How to investigate and monitor it', terms: 'monitor|monitoring|compare features|log predictions|shadow|backtest|feature distribution|alert' },
    ],
    model:
      'The first suspect is leakage: a feature that would not exist at prediction time, such as a field filled in after the outcome, or a random split that lets the same user appear in train and test. The second is training and serving skew, where production computes a feature differently from the notebook. The third is drift, where the real data has moved since training. I would log production inputs and predictions, compare feature distributions against training, rebuild validation with a time based split, and check each top feature for whether it is really available at prediction time.',
    hints: ['List at least three causes.', 'Say how you would confirm which one it is.'],
    next: 'How would you set up monitoring so this is caught within a day next time?',
  },
  {
    id: 'ds-ab-significance',
    roles: ['data-scientist', 'data-analyst', 'product-manager'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'An A/B test shows a 3 percent lift in conversion. How do you decide whether to trust it and ship?',
    anchors: 'a b test|ab test|experiment|lift|conversion|variant|control|significan',
    points: [
      { label: 'Statistical significance and confidence interval', terms: 'significant|significance|p value|confidence interval|statistical|power|sample size' },
      { label: 'Checked the test ran correctly, such as sample ratio and duration', terms: 'sample ratio|srm|randomization|randomisation|full week|duration|novelty|peeking|stopped early' },
      { label: 'Guardrail metrics did not get worse', terms: 'guardrail|revenue|retention|refund|latency|counter metric|side effect|other metrics' },
      { label: 'Segments and practical size of the effect', terms: 'segment|mobile|desktop|new users|practical|business impact|worth it|cost' },
    ],
    model:
      'I check four things. Was it significant: the confidence interval for the lift should exclude zero and the test should have hit the sample size we planned, not been stopped the moment it looked good. Did it run cleanly: the traffic split should match what we set, and it should cover at least one full weekly cycle to avoid day of week and novelty effects. Did guardrails hold: revenue per user, refunds or page speed should not get worse. Is it real for the business: a 3 percent lift on a small segment may not be worth the maintenance. If all four pass, I ship and keep watching the metric after launch.',
    hints: ['Cover significance, test health and guardrails.', 'Mention one way tests are often misread.'],
    next: 'What would you do if the result is positive overall but negative on mobile?',
  },

  // ------------------------------------------------------------- Data analyst
  {
    id: 'da-joins',
    roles: ['data-analyst', 'data-scientist', 'backend-developer'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'Explain the difference between an INNER JOIN and a LEFT JOIN, and give an example of when the choice changes your answer.',
    anchors: 'join|inner|left|sql|table|rows',
    points: [
      { label: 'Inner join keeps only matching rows', terms: 'only matching|only rows that match|both tables|match in both|intersection|inner join' },
      { label: 'Left join keeps every row from the left table, with nulls when no match', terms: 'all rows from the left|every row from the left|keeps all|null|nulls|no match|left join' },
      { label: 'A concrete example where the result differs', terms: 'customers|orders|users|never ordered|no orders|zero|count|missing|signed up' },
      { label: 'Watch for duplicates or filters that change the join', terms: 'duplicate|duplicates|one to many|fan out|where clause|filter in the on|turns into an inner join' },
    ],
    model:
      'An INNER JOIN returns only rows that have a match in both tables. A LEFT JOIN returns every row from the left table, and fills the right side with nulls where there is no match. Say I want the number of orders per customer. With an inner join on customers and orders, customers who never ordered disappear, so the average orders per customer looks higher than it is. A LEFT JOIN keeps them with a count of zero. One trap: putting a condition on the right table in the WHERE clause removes those null rows and quietly turns the LEFT JOIN back into an inner join, so that condition belongs in the ON clause.',
    hints: ['Define both in one sentence each.', 'Use customers and orders, or a similar example.'],
    next: 'How would you find customers who have never placed an order?',
  },
  {
    id: 'da-window-functions',
    roles: ['data-analyst', 'data-scientist'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'What are window functions in SQL? Give an example where you would use one instead of GROUP BY.',
    anchors: 'window|over|partition|group by|sql|row number|rank',
    points: [
      { label: 'Computes across related rows without collapsing them', terms: 'without collapsing|keeps every row|keeps the rows|each row|does not collapse|not grouped|row level' },
      { label: 'OVER with PARTITION BY and ORDER BY', terms: 'over|partition by|order by|frame|rows between' },
      { label: 'Named real functions', terms: 'row number|rank|dense rank|lag|lead|running total|sum over|moving average|ntile' },
      { label: 'A concrete use case', terms: 'latest order|top 3|top three|per customer|running total|month over month|previous|first purchase|dedupe|deduplicate' },
    ],
    model:
      'A window function calculates across a set of related rows but keeps every row in the result, while GROUP BY collapses each group into one row. You write it with OVER, using PARTITION BY to define the group and ORDER BY to set the order inside it. For example, to get each customer\'s most recent order with all its details, I use ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC) and keep row 1. GROUP BY could give me the latest date, but not the rest of that order\'s columns without another join. I also use LAG for month over month change and SUM OVER for running totals.',
    hints: ['Contrast it with GROUP BY.', 'Write or describe one real query.'],
    next: 'What is the difference between RANK and DENSE_RANK?',
  },
  {
    id: 'da-cleaning',
    roles: ['data-analyst'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'You receive a messy sales spreadsheet from another team. Walk me through how you clean it before analysis.',
    anchors: 'clean|cleaning|messy|spreadsheet|data|sales',
    points: [
      { label: 'Profile the data first', terms: 'profile|explore|look at|summary|row count|data types|distinct values|understand the columns' },
      { label: 'Duplicates', terms: 'duplicate|duplicates|dedupe|deduplicate|same order twice|unique id' },
      { label: 'Formats and types such as dates, currency and text', terms: 'date format|dates|currency|data type|text to number|trim|whitespace|case|standardize|standardise|consistent' },
      { label: 'Missing values and outliers', terms: 'missing|blank|null|outlier|outliers|negative|impossible|out of range' },
      { label: 'Validate against a known total and document changes', terms: 'reconcile|known total|check against|validate|document|log the changes|ask the team|source system' },
    ],
    model:
      'I keep the original untouched and work on a copy. First I profile it: row count, column types, distinct values and blanks, so I know what I am dealing with. Then I fix structure: trim spaces, make text case consistent, convert dates and currency to one format, and turn numbers stored as text into numbers. Next I remove exact duplicates and check for near duplicates using the order ID. I flag blanks and odd values, such as negative quantities, and ask the owning team about them instead of guessing. Finally I reconcile the total revenue against a number the team already trusts and write down every change I made.',
    hints: ['Go step by step, in the order you would really do it.', 'Say how you know the cleaned data is right.'],
    next: 'What would you do if your cleaned total does not match the finance report?',
  },
  {
    id: 'da-metric-drop',
    roles: ['data-analyst', 'data-scientist', 'product-manager'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Daily active users dropped 20 percent yesterday. How do you investigate?',
    anchors: 'drop|dropped|daily active|dau|users|decline|fell',
    points: [
      { label: 'Check whether the data itself is broken', terms: 'tracking|logging|pipeline|data issue|broken|instrumentation|event|etl|bug in the data|dashboard' },
      { label: 'Check for external or calendar causes', terms: 'holiday|weekend|seasonal|outage|competitor|news|external|app store|same day last' },
      { label: 'Segment the drop to find where it is', terms: 'segment|platform|ios|android|web|country|region|version|new users|channel|break it down' },
      { label: 'Look for internal changes such as releases or experiments', terms: 'release|deploy|launch|experiment|feature flag|change|update|marketing campaign' },
      { label: 'Communicate and size the impact', terms: 'communicate|stakeholder|update|impact|hypothesis|next steps|escalate' },
    ],
    model:
      'First I check whether the drop is real. A tracking change, a broken pipeline or a late data load causes many of these, so I compare against a second source like server logs. If it is real, I check the calendar and outside events: a holiday, an outage or an app store problem. Then I break the drop down by platform, country, app version and acquisition channel. If it sits entirely in Android on the newest version, I look at what shipped yesterday and which experiments started. I share a short update early with what I have ruled out, then the cause and its size once confirmed.',
    hints: ['Rule out data problems first.', 'Explain how you would narrow it down.'],
    next: 'Suppose the drop is only on Android version 5.2. What do you do next?',
  },
  {
    id: 'da-dashboard-kpi',
    roles: ['data-analyst'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'How do you decide which metrics go on a dashboard for a business team?',
    anchors: 'dashboard|metric|metrics|kpi|kpis|stakeholder',
    points: [
      { label: 'Start from the decisions the team makes', terms: 'decision|decisions|question|questions|goal|goals|what they need|stakeholder|interview' },
      { label: 'Few headline metrics, with definitions', terms: 'few|small number|headline|north star|definition|define|single source|consistent' },
      { label: 'Context such as targets, trends and comparisons', terms: 'target|trend|over time|compare|comparison|last week|last year|benchmark|goal line' },
      { label: 'Drill down and layout', terms: 'drill down|filter|filters|segment|layout|top left|hierarchy|detail' },
      { label: 'Check that it is actually used', terms: 'usage|used|adoption|feedback|iterate|review|retire' },
    ],
    model:
      'I start by asking the team what decisions they make each week and what would change those decisions. That gives me three to five headline metrics, each with a written definition so nobody argues about what active customer means. Each number gets context: a trend line, a comparison to last period and the target, because a number on its own does not tell anyone whether to act. Below that I add filters and drill downs by region or product for the follow up questions. After launch I check usage and ask for feedback, and remove charts nobody looks at.',
    hints: ['Start from the people who use it.', 'Explain how you keep it simple.'],
    next: 'How would you handle two teams that define the same metric differently?',
  },

  // ---------------------------------------------------------- Product manager
  {
    id: 'pm-prioritize',
    roles: ['product-manager'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'You have twenty feature requests and capacity for three this quarter. How do you prioritize?',
    anchors: 'priorit|feature|request|backlog|roadmap|capacity',
    points: [
      { label: 'Tie the choice to goals or strategy', terms: 'goal|goals|strategy|objective|okr|okrs|north star|company priority' },
      { label: 'Use a framework or scoring method', terms: 'rice|ice|reach|impact|confidence|effort|moscow|kano|value versus effort|value vs effort|cost of delay' },
      { label: 'Use evidence about users and impact', terms: 'data|evidence|users|customers|research|how many customers|revenue|churn|support tickets' },
      { label: 'Involve engineering for effort and risk', terms: 'engineering|engineers|estimate|effort|complexity|risk|dependency|dependencies' },
      { label: 'Communicate the decision and what is not happening', terms: 'communicate|stakeholder|say no|explain|roadmap|not now|later|transparent' },
    ],
    model:
      'I start from this quarter\'s goal, for example improving activation, and drop anything that does not move it. For what remains, I score each request with RICE: how many users it reaches, the likely impact, how confident we are from data or research, and the effort the engineers estimate. I sanity check the top of the list against things scores miss, like a commitment to a key customer or a security risk. Then I share the three picks with the reasons, and tell the people behind the other requests why they are not in this quarter and what would change that.',
    hints: ['Name the method you would use.', 'Say how you handle people whose requests lose.'],
    next: 'A sales leader insists their request must be in the top three. What do you do?',
  },
  {
    id: 'pm-success-metrics',
    roles: ['product-manager'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'We are launching a saved searches feature. How would you measure whether it is successful?',
    anchors: 'metric|metrics|measure|success|saved search|launch|feature',
    points: [
      { label: 'Define the goal of the feature first', terms: 'goal|why we built|problem|purpose|user need|hypothesis' },
      { label: 'Adoption metric', terms: 'adoption|create a saved search|percentage of users|how many users|usage|activation|first use' },
      { label: 'Engagement or retention metric', terms: 'return|retention|come back|repeat|frequency|weekly|engagement|alerts opened' },
      { label: 'Business outcome', terms: 'conversion|revenue|purchase|bookings|business|outcome|north star' },
      { label: 'Guardrail metric', terms: 'guardrail|counter metric|cannibal|unsubscribe|complaints|performance|side effect|email fatigue' },
    ],
    model:
      'First the goal: saved searches should bring users back without them needing to search from scratch, and lead to more purchases. For adoption, I track the share of active searchers who save at least one search in their first week. For engagement, how many come back through a saved search or its alert within thirty days, compared with similar users who did not save one. For the business, the conversion rate of sessions that start from a saved search. As a guardrail, I watch email unsubscribes, because too many alerts can push people away. I set targets before launch so we do not pick the good numbers afterwards.',
    hints: ['Start with the goal.', 'Give adoption, engagement, business and guardrail metrics.'],
    next: 'Adoption is high but conversion did not change. What does that tell you?',
  },
  {
    id: 'pm-deadline-risk',
    roles: ['product-manager', 'engineering-manager'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Engineering tells you a launch promised to customers will slip by three weeks. What do you do?',
    anchors: 'launch|slip|delay|deadline|late|engineering|customers',
    points: [
      { label: 'Understand the cause and confidence of the new date', terms: 'understand why|root cause|why it slipped|what changed|confidence|new estimate|blocker' },
      { label: 'Explore scope options to protect the date', terms: 'scope|cut scope|reduce scope|mvp|phase|phased|smaller version|must have|descope' },
      { label: 'Communicate early to stakeholders and customers', terms: 'communicate|tell|inform|stakeholder|customers|sales|leadership|early|transparent' },
      { label: 'Agree a decision and a revised plan', terms: 'decision|decide|tradeoff|trade off|plan|revised|options|recommend' },
      { label: 'Learn from it to avoid repeats', terms: 'retro|retrospective|learn|lesson|next time|buffer|estimate better|process' },
    ],
    model:
      'I sit down with the tech lead to understand what changed and how confident the new date is, without blaming anyone. Then we look at options: cutting scope so the core of what customers were promised still ships on time, splitting it into two releases, or accepting the delay. I bring a recommendation to the stakeholders the same week, so sales can talk to customers before the date passes instead of after. Once we agree, I update the plan and send one clear note. Afterwards we hold a short retro on why the risk showed up late and how to spot it sooner.',
    hints: ['Show that you look for options, not just a new date.', 'Say who you tell and when.'],
    next: 'What if the customer contract has a penalty for missing the date?',
  },
  {
    id: 'pm-validate-need',
    roles: ['product-manager'],
    category: 'technical',
    levels: ['entry', 'mid'],
    question: 'How do you validate that a problem is worth solving before the team builds anything?',
    anchors: 'validate|problem|users|research|build|worth',
    points: [
      { label: 'Talk to users with open questions', terms: 'interview|interviews|talk to users|talk to customers|user research|open questions|past behaviour|past behavior' },
      { label: 'Use existing data and signals', terms: 'data|analytics|support tickets|tickets|reviews|search logs|usage|feedback|sales calls' },
      { label: 'Size the problem', terms: 'how many|size|frequency|how often|market|segment|impact|pain' },
      { label: 'Test cheaply with a prototype or experiment', terms: 'prototype|mockup|fake door|landing page|smoke test|concierge|experiment|wizard of oz|test' },
    ],
    model:
      'I look for evidence in three places. First, existing signals: support tickets, sales notes, reviews and product data on where people get stuck. Second, interviews with five to eight users about the last time they hit the problem and what they did about it, because what people did is more reliable than what they say they would do. Third, a cheap test, such as a clickable prototype or a fake door button that measures how many people try to use it. If the problem comes up often, affects a meaningful segment and people already spend effort working around it, it is worth building for.',
    hints: ['Use more than one source of evidence.', 'Include one cheap way to test before building.'],
    next: 'How would you write interview questions that avoid leading the user?',
  },
  {
    id: 'pm-build-buy',
    roles: ['product-manager', 'engineering-manager', 'system-architect'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Should we build our own payments flow or use a provider like Stripe? How do you make that call?',
    anchors: 'build|buy|vendor|provider|stripe|payment|payments|third party',
    points: [
      { label: 'Is it core to how we win', terms: 'core|differentiator|differentiate|competitive advantage|strategic|commodity' },
      { label: 'Total cost, not only the fee', terms: 'cost|fees|total cost|maintenance|engineering time|headcount|ongoing' },
      { label: 'Time to market', terms: 'time to market|speed|faster|weeks|months|launch sooner' },
      { label: 'Risk, compliance and security', terms: 'compliance|pci|security|fraud|risk|regulation|liability' },
      { label: 'Lock in and flexibility', terms: 'lock in|vendor lock|switch|flexibility|control|customization|customisation|exit' },
    ],
    model:
      'The main question is whether payments is how we win or just something we need to work. For most companies it is the second, so I lean towards a provider. Building means PCI compliance, fraud handling and supporting every payment method, which is ongoing engineering time, not a one off project. A provider gets us live in weeks. The costs are transaction fees, which grow with volume, and some lock in. I would compare total cost at our expected volume over two or three years, and keep our own thin layer around the provider so switching later is possible. If we reach a scale where fees are a large share of margin, we revisit.',
    hints: ['Give the criteria you would use.', 'Say what would change your answer.'],
    next: 'At what point would you revisit the decision?',
  },

  // ------------------------------------------------------ Engineering manager
  {
    id: 'em-underperformer',
    roles: ['engineering-manager'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'One engineer on your team is consistently missing commitments. How do you handle it?',
    anchors: 'underperform|performance|engineer|missing|commitments|struggling',
    points: [
      { label: 'Find the cause before judging', terms: 'understand|find out why|root cause|personal|unclear|skills|blocked|motivation|listen' },
      { label: 'Give clear, specific feedback early', terms: 'feedback|specific|examples|direct|early|honest|private|one to one|1 1' },
      { label: 'Agree clear expectations and a plan', terms: 'expectations|goals|plan|measurable|support|pair|mentor|smaller tasks|check in' },
      { label: 'Follow up and document', terms: 'follow up|review|weekly|track|document|progress' },
      { label: 'Know the next step if it does not improve', terms: 'hr|performance plan|pip|escalate|consequence|role change|part ways|let go' },
    ],
    model:
      'I raise it early and privately, with specific examples rather than a general feeling, and then I listen, because the cause might be unclear tasks, a skills gap, being blocked by another team, or something personal. Once I understand it, we agree on clear expectations for the next few weeks and the support I will give, such as smaller tasks, pairing with a senior engineer or removing a blocker. We check progress weekly and I write down what we agreed. Most people improve with clarity and support. If they do not, I involve HR and move to a formal plan, and they will not be surprised, because we have talked about it every week.',
    hints: ['Show you look for the cause first.', 'Say what happens if nothing improves.'],
    next: 'How would you handle it if the engineer says the problem is unclear requirements from product?',
  },
  {
    id: 'em-tech-debt',
    roles: ['engineering-manager', 'system-architect'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'Product wants new features every sprint, but tech debt is slowing the team down. How do you balance the two?',
    anchors: 'tech debt|technical debt|debt|features|refactor|legacy',
    points: [
      { label: 'Make the cost of debt visible with evidence', terms: 'evidence|data|cycle time|incidents|bugs|velocity|lead time|cost|slows us|measure' },
      { label: 'Frame it in business terms', terms: 'business|customers|revenue|risk|speed of delivery|outcome|product' },
      { label: 'A steady allocation or plan', terms: 'percent|percentage|allocation|budget|each sprint|20|fixed share|roadmap|reserve' },
      { label: 'Prioritize the debt that hurts most', terms: 'prioritize|prioritise|highest impact|most painful|hot spots|areas we change often|worst' },
      { label: 'Partner with product rather than fight', terms: 'partner|together|agree|product manager|trust|collaborate|shared' },
    ],
    model:
      'I make the cost visible first, because "the code is messy" does not win arguments. I bring numbers such as how long changes take in the worst areas, how many incidents came from them, or how often a small feature turned into a two week job. Then I put it in business terms with the product manager: fixing the checkout module makes every future checkout feature faster. We agree on a steady share of each sprint, often around a fifth, for the debt that slows us most, focused on code we change often rather than code that is ugly but stable. Bigger rewrites go on the roadmap as their own items.',
    hints: ['Show how you make the cost visible.', 'Say how you agree the split with product.'],
    next: 'How would you convince leadership to fund a quarter long rewrite?',
  },
  {
    id: 'em-one-on-ones',
    roles: ['engineering-manager'],
    category: 'technical',
    levels: ['entry', 'mid', 'senior'],
    question: 'How do you run one on one meetings with your engineers?',
    anchors: 'one on one|1 1|1:1|one on ones|meeting|engineers',
    points: [
      { label: 'Regular and protected', terms: 'weekly|every week|biweekly|every two weeks|regular|never cancel|protected|consistent' },
      { label: 'Their meeting, their agenda', terms: 'their agenda|their meeting|they set|shared doc|agenda|their topics' },
      { label: 'Career growth and goals', terms: 'career|growth|goals|promotion|development|aspirations|learning' },
      { label: 'Two way feedback', terms: 'feedback|two way|both directions|about me|what i can do better' },
      { label: 'Notes and follow through', terms: 'notes|follow up|follow through|action items|track|remember' },
    ],
    model:
      'I hold them weekly for thirty minutes and almost never cancel, because moving them tells people they are not a priority. It is their meeting: we keep a shared doc where they add topics first, and status updates belong in standup, not here. I use the time for how they are doing, what is blocking them, and their growth, with a deeper career conversation about once a month. I give feedback in both directions and ask what I could do better. I write short notes with any action items, and I start the next one by following up on what I promised.',
    hints: ['Say how often and what you cover.', 'Explain how it differs from a status meeting.'],
    next: 'What do you do when an engineer has nothing to talk about in their one on one?',
  },
  {
    id: 'em-hiring',
    roles: ['engineering-manager'],
    category: 'technical',
    levels: ['mid', 'senior'],
    question: 'How would you design a fair hiring process for engineers on your team?',
    anchors: 'hiring|hire|interview|candidates|recruit|process',
    points: [
      { label: 'Define the role and what good looks like first', terms: 'job description|role|define|competencies|criteria|what good looks like|scorecard|requirements|first year|what we assess|assess|writing down|write down' },
      { label: 'Structured interviews with a rubric', terms: 'structured|rubric|same questions|consistent|scoring|score|calibrate|calibration' },
      { label: 'Work sample close to the real job', terms: 'work sample|take home|pairing|pair programming|realistic|real problem|practical|code review' },
      { label: 'Reduce bias', terms: 'bias|diverse panel|independent|before discussing|blind|fair|inclusive' },
      { label: 'Good candidate experience and fast decisions', terms: 'candidate experience|feedback to candidates|give feedback|tell candidates|what to expect|fast|quick|timeline|two weeks|respect' },
    ],
    model:
      'I start by writing down what the person will actually do in the first year and turn that into four or five things we assess, each with a clear rubric. Every candidate gets the same structured interviews so we are comparing like with like. For the technical part I prefer a work sample close to the job, such as pairing on a small realistic task or reviewing a pull request, over puzzles. Interviewers write their scores independently before the debrief so the loudest voice does not decide. And I keep the whole process to about two weeks, tell candidates what to expect, and give feedback when we say no.',
    hints: ['Cover structure, assessment and bias.', 'Mention the candidate side too.'],
    next: 'How do you calibrate interviewers so they score consistently?',
  },
  {
    id: 'em-productivity',
    roles: ['engineering-manager'],
    category: 'technical',
    levels: ['senior'],
    question: 'Leadership asks you to measure your team\'s productivity. What would you measure, and what would you avoid?',
    anchors: 'productivity|measure|metrics|team|performance|velocity',
    points: [
      { label: 'Delivery metrics such as the DORA measures', terms: 'dora|deployment frequency|lead time|change failure rate|time to restore|mttr|cycle time' },
      { label: 'Outcomes, not just output', terms: 'outcome|outcomes|impact|customer|business|goals|value delivered' },
      { label: 'Avoid individual activity metrics', terms: 'lines of code|commits|story points|individual|gaming|goodhart|vanity|ranking people' },
      { label: 'Include team health', terms: 'health|survey|developer experience|satisfaction|burnout|morale|space' },
      { label: 'Use them to improve, not to judge', terms: 'improve|trends|conversation|context|not to judge|not for performance reviews|team level' },
    ],
    model:
      'I would measure at the team level, not per person. For delivery, the DORA metrics: deployment frequency, lead time for changes, change failure rate and time to restore service. Alongside those, outcomes: did the work move the goals we set this quarter. And team health, through a short regular survey on things like focus time and friction in the tooling. I would avoid lines of code, commit counts or story points per person, because people optimize for whatever is counted and it damages trust. I would present trends with context and use them to find what is slowing us down, not to rank engineers.',
    hints: ['Name specific metrics.', 'Say what you would not measure and why.'],
    next: 'Lead time doubled last month. How do you find out why?',
  },
];
