import type { BankQuestion } from './bank-types';

// Behavioral questions apply to every role. Each one has theme specific key
// points; the STAR structure itself is scored separately by the checker.

const STAR_HINTS = [
  'Pick one real situation and say when and where it happened.',
  'Say what you personally did, using "I", not only what the team did.',
  'Finish with the result, ideally a number, and what you learned.',
];

export const BEHAVIORAL: BankQuestion[] = [
  {
    id: 'b-conflict',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Tell me about a time you disagreed with a teammate or your manager. How did you handle it?',
    anchors: 'disagree|disagreement|conflict|pushback|push back|different opinion|different view|argued|argument|tension|objected|concern',
    points: [
      { label: 'Explained what the disagreement was about', terms: 'disagree|disagreement|they wanted|i thought|i believed|different approach|different opinion|conflict' },
      { label: 'Showed you understood the other person’s view', terms: 'listen|listened|understand their|understand his|understand her|their perspective|their concern|asked why|their point|their reasons|his reasons|her reasons|why he|why she|why they|heard|his concern|her concern' },
      { label: 'Used facts or data rather than opinion', terms: 'data|evidence|benchmark|prototype|numbers|metrics|test|experiment|proof of concept' },
      { label: 'Reached a resolution or compromise', terms: 'agreed|compromise|resolved|middle ground|decided|aligned|consensus|went with' },
      { label: 'Kept the working relationship healthy', terms: 'relationship|respect|trust|stayed friendly|work well together|still work|thanked' },
    ],
    model:
      'On a checkout rebuild, my lead wanted to rewrite the payment module from scratch and I thought a staged refactor was safer. I asked for a short one to one to understand his reasons, which were mainly about test coverage. I proposed a two day spike: I refactored one payment path behind a feature flag and added the missing tests, then we compared the effort. The data showed the refactor was about a third of the time with less risk, so we went with it and shipped two weeks early. We still work closely, and I learned to bring a small experiment instead of an opinion.',
    hints: STAR_HINTS,
    next: 'Looking back, is there anything you would have done differently in that conversation?',
  },
  {
    id: 'b-failure',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Tell me about a time you made a mistake at work. What happened and what did you do about it?',
    anchors: 'mistake|failed|failure|error|went wrong|broke|bug|outage|missed|wrong',
    points: [
      { label: 'Owned the mistake clearly', terms: 'my mistake|i made|my fault|i was responsible|i caused|i missed|i forgot|i broke|i took responsibility|owned' },
      { label: 'Described the impact honestly', terms: 'impact|affected|customers|users|lost|downtime|delay|cost|broke' },
      { label: 'Explained how you fixed it', terms: 'fixed|rolled back|rollback|patched|corrected|resolved|hotfix|recovered' },
      { label: 'Told the right people quickly', terms: 'told|informed|escalated|communicated|let my manager|raised|flagged|alerted' },
      { label: 'Put something in place so it does not happen again', terms: 'prevent|checklist|test|alert|process|automation|review|never again|since then|now i' },
    ],
    model:
      'In my first year I ran a database migration on Friday afternoon that locked a large table, and the order page timed out for about twenty minutes. I noticed the alerts, told my lead straight away and rolled the migration back. Then I rewrote it to run in small batches and ran it on Monday morning with no downtime. I also added a staging check for migrations that touch big tables and wrote a short guide for the team. It was my mistake, and the fix was to change the process, not only the script.',
    hints: STAR_HINTS,
    next: 'How did your manager or team react, and what did that teach you about raising problems early?',
  },
  {
    id: 'b-deadline',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Describe a time you had a tight deadline you could not meet as planned. What did you do?',
    anchors: 'deadline|time pressure|tight|late|behind schedule|due|launch date|ran out of time|timeline',
    points: [
      { label: 'Spotted the risk early', terms: 'early|realised|realized|noticed|saw that|flagged|risk|behind' },
      { label: 'Prioritised what really mattered', terms: 'prioritis|prioritiz|must have|most important|core|mvp|cut scope|reduce scope|descoped|focus on' },
      { label: 'Communicated with stakeholders', terms: 'told|communicated|stakeholder|manager|client|updated|expectations|negotiated' },
      { label: 'Explained the trade off you accepted', terms: 'trade off|tradeoff|instead|later|follow up|phase two|second release|technical debt' },
      { label: 'Gave the outcome', terms: 'delivered|shipped|launched|on time|met the|result|outcome' },
    ],
    model:
      'We had three weeks to launch a partner integration and halfway through I realised the reporting part alone needed two more weeks. I told my manager and the partner immediately and listed what was essential for launch day: orders syncing correctly. We agreed to ship the sync on time and deliver reporting as a second release. I wrote a simple CSV export as a stopgap. We launched on the original date with zero sync errors, and reporting followed ten days later. Raising it early is what made the trade off acceptable to everyone.',
    hints: STAR_HINTS,
    next: 'How do you decide what to cut when everything feels important?',
  },
  {
    id: 'b-ownership',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Tell me about a time you took ownership of a problem that was not strictly your job.',
    anchors: 'ownership|own|not my job|outside my|stepped up|took on|volunteered|nobody owned|initiative',
    points: [
      { label: 'Explained why nobody else was handling it', terms: 'nobody|no one|not my|outside my|fell between|fell through|no owner|no team|no engineering team|nobody owned|not assigned|unowned|between teams|kept forwarding|ignored|not anyone' },
      { label: 'Took the first step yourself', terms: 'i decided|i started|i volunteered|i took|stepped up|took ownership|i built|i wrote|i set up|i asked|i offered|i proposed|i fixed|i went through|i spent|i dug' },
      { label: 'Involved the right people', terms: 'asked|involved|team|manager|permission|agreed|aligned' },
      { label: 'Showed the result', terms: 'result|reduced|improved|saved|fixed|now|outcome|%|percent' },
    ],
    model:
      'Our support team kept forwarding the same login complaints and no engineering team owned the auth flow. I asked my manager if I could spend a few days on it, then went through a month of tickets and found two causes: an expired token not being refreshed and an unclear error message. I fixed the refresh logic and rewrote the message with the support lead. Login tickets fell by about 60 percent the next month, and the auth flow was formally assigned to our team afterwards.',
    hints: STAR_HINTS,
    next: 'How did you balance this with the work you were actually assigned?',
  },
  {
    id: 'b-feedback',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Tell me about a time you received critical feedback. How did you respond?',
    anchors: 'feedback|criticism|critical|told me|review|performance review|pointed out',
    points: [
      { label: 'Said what the feedback actually was', terms: 'feedback was|told me|said that|pointed out|my manager said|criticism' },
      { label: 'Showed you listened without getting defensive', terms: 'listened|accepted|thanked|asked for examples|asked for two|asked for specific|did not argue|instead|reflected|agreed|took it|first reaction|looked at them' },
      { label: 'Made a concrete change', terms: 'changed|started|now i|i began|practised|practiced|improved|plan|habit' },
      { label: 'Showed the change worked', terms: 'later|next review|result|noticed|improved|better|since then' },
    ],
    model:
      'In a review my lead told me my pull requests were too large and hard to review, which slowed the whole team. My first reaction was to explain why, but instead I asked for two examples and looked at them with her. I started splitting work into smaller pull requests of under 300 lines and writing a short summary at the top of each one. Over the next quarter my average review time dropped from three days to under one, and she mentioned it as a strength in my next review.',
    hints: STAR_HINTS,
    next: 'Tell me about a time you had to give difficult feedback to someone else.',
  },
  {
    id: 'b-influence',
    roles: '*',
    category: 'behavioral',
    levels: ['mid', 'senior'],
    question: 'Describe a time you had to convince people to change direction without having formal authority over them.',
    anchors: 'convince|persuade|influence|buy in|without authority|change direction|get them to|adopt',
    points: [
      { label: 'Explained what you wanted to change and why', terms: 'proposed|wanted to|i wanted|suggested|switch|adopt|move to|instead of|introduce|replace|share one|standardize|standardise' },
      { label: 'Understood what the others cared about', terms: 'their concern|their concerns|their goal|what they cared|their priorities|asked them|asked what|asked each|met each|met with|what slowed|their pain|listened|understood|one to one|mentioned' },
      { label: 'Used evidence or a small pilot', terms: 'data|pilot|prototype|demo|experiment|proof|numbers|trial|small test' },
      { label: 'Built allies or support', terms: 'ally|allies|support|champion|one team|got buy in|lead agreed|early adopter' },
      { label: 'Shared the outcome', terms: 'adopted|agreed|result|now|outcome|reduced|improved|joined|cut|half|percent|switched|signed off' },
    ],
    model:
      'I wanted the three product teams to share one design system instead of copying components, but I led none of them. I met each lead to ask what slowed them down, and all three mentioned inconsistent UI bugs. I built a small pilot with the five most used components and moved one team onto it first. That team cut UI bugs in half within a sprint, and I shared those numbers at the engineering meeting. The other two teams joined the next quarter.',
    hints: STAR_HINTS,
    next: 'What would you have done if one team had refused to adopt it?',
  },
  {
    id: 'b-ambiguity',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Tell me about a time you had to work with unclear or changing requirements.',
    anchors: 'unclear|ambiguous|ambiguity|changing requirements|changed|vague|not defined|uncertain|moving target',
    points: [
      { label: 'Described what was unclear', terms: 'unclear|vague|ambiguous|no spec|not defined|kept changing|changed' },
      { label: 'Asked questions to clarify', terms: 'asked|clarify|clarified|questions|met with|talked to|workshop|user' },
      { label: 'Made assumptions explicit or wrote them down', terms: 'assumption|assumed|wrote down|documented|spec|one pager|confirmed' },
      { label: 'Delivered in small steps to learn quickly', terms: 'small|iteration|iterate|prototype|mvp|first version|feedback|incremental' },
      { label: 'Gave the result', terms: 'result|shipped|delivered|outcome|launched|users' },
    ],
    model:
      'I was asked to build a reporting page for our sales team with only one sentence of requirements. I booked thirty minutes with two sales reps and asked which decisions the report should help them make. I wrote down three assumptions and confirmed them with the sales manager by message. Then I shipped a simple first version in a week and watched how they used it. They ignored two charts and asked for one filter, so the second version was smaller and more useful. Usage went from zero to daily within a month.',
    hints: STAR_HINTS,
    next: 'How do you decide when you have enough information to start building?',
  },
  {
    id: 'b-learn',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid'],
    question: 'Tell me about a time you had to learn something new very quickly to get the job done.',
    anchors: 'learn|learned|learnt|new technology|new tool|unfamiliar|never used|pick up|ramp up|quickly',
    points: [
      { label: 'Said what you had to learn and why', terms: 'had to learn|never used|never written|never done|had never|new to|unfamiliar|first time|needed to learn|did not know|didnt know|had not used|no experience' },
      { label: 'Explained how you learned', terms: 'documentation|docs|tutorial|course|built a|small project|asked|mentor|pair|read' },
      { label: 'Applied it to the real task', terms: 'applied|used it|built|implemented|delivered|shipped|rewrote|i then|fixed|set up|migrated|wrote' },
      { label: 'Gave the outcome', terms: 'result|on time|delivered|shipped|worked|outcome|weeks|days' },
    ],
    model:
      'Two weeks before a release our only Docker expert left, and I was asked to fix the build pipeline though I had never written a Dockerfile. I spent the first evening on the official docs and rebuilt a tiny sample app in a container. The next day I paired for an hour with an engineer from another team to review my plan. I then rewrote our Dockerfile, cut the image size from 1.2 GB to 300 MB and fixed the failing builds. We released on time, and I wrote a short guide so the next person would not start from zero.',
    hints: STAR_HINTS,
    next: 'How do you usually decide what to learn deeply and what to learn just enough of?',
  },
  {
    id: 'b-proud',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'What is the project you are most proud of, and what was your specific contribution?',
    anchors: 'proud|project|built|launched|shipped|led|created|delivered',
    points: [
      { label: 'Explained the problem the project solved', terms: 'problem|goal|needed|because|users|customers|business' },
      { label: 'Made your own contribution clear', terms: 'i built|i designed|i wrote|i led|my part|my role|i was responsible|i implemented' },
      { label: 'Mentioned a real technical or practical challenge', terms: 'challenge|difficult|hard|problem|issue|tricky|constraint' },
      { label: 'Gave a measurable result', terms: '%|percent|users|reduced|increased|saved|faster|revenue|hours|minutes|seconds' },
    ],
    model:
      'I am proudest of rebuilding our search, because customers could not find products and support blamed it for lost sales. I designed the new index and wrote the ranking logic, while a teammate built the UI. The hard part was handling typos and plurals without slowing the page down, which I solved with a precomputed synonym table. After launch, searches that returned zero results fell from 18 percent to 4 percent, and search led orders went up about 12 percent in the first month.',
    hints: STAR_HINTS,
    next: 'If you rebuilt it today, what would you change?',
  },
  {
    id: 'b-customer',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Tell me about a time you went out of your way to solve a problem for a user or customer.',
    anchors: 'customer|user|client|support ticket|complaint|feedback|users',
    points: [
      { label: 'Described the user problem', terms: 'customer|user|client|complained|reported|struggling|issue|ticket' },
      { label: 'Found the real cause', terms: 'root cause|found that|realised|realized|investigated|dug into|looked at' },
      { label: 'Went beyond the minimum', terms: 'extra|beyond|went out of my way|personally|myself|called|followed up|on my own time|reran|sent them|added a test|so it would not happen|weekend|evening' },
      { label: 'Gave the outcome for the user', terms: 'happy|resolved|thanked|renewed|stayed|result|fewer|reduced' },
    ],
    model:
      'A long time customer reported that exports were missing rows, and support had closed the ticket twice as user error. I asked for their file and found that rows with emoji in the name were silently dropped by our CSV encoder. I fixed the encoder, reran their last three months of exports and sent them the corrected files myself with a short explanation. They renewed their contract that quarter, and we added a test for unusual characters so it would not happen to anyone else.',
    hints: STAR_HINTS,
    next: 'How do you balance one customer’s request against the needs of all users?',
  },
  {
    id: 'b-mentor',
    roles: '*',
    category: 'behavioral',
    levels: ['mid', 'senior'],
    question: 'Tell me about a time you helped a teammate grow or improve.',
    anchors: 'mentor|mentored|coached|helped|teammate|junior|grow|onboard|taught',
    points: [
      { label: 'Described where the person was struggling', terms: 'struggling|new|junior|stuck|difficult|lacked|needed help' },
      { label: 'Explained how you helped', terms: 'pair|paired|reviewed|taught|explained|one to one|weekly|guide|showed' },
      { label: 'Let them do the work themselves', terms: 'let them|let him|let her|own|ownership|on their own|on his own|on her own|independent|they led|he led|she led|gave them|instead of fixing|lead the|asked him|asked her|asked them' },
      { label: 'Showed their progress', terms: 'now|later|promoted|independently|improved|result|confident|fewer|grew|within a|after a|reviews code|mentors' },
    ],
    model:
      'A new developer on my team was shipping features but kept getting the same review comments about error handling. I suggested a weekly thirty minute pairing session. Instead of fixing his code I asked him to talk through what could fail at each step. After a month I let him lead the design for a small service on his own and only reviewed the plan. Within a quarter his pull requests needed far fewer changes, and he now reviews code for newer team members.',
    hints: STAR_HINTS,
    next: 'How do you adjust your approach for someone who learns very differently from you?',
  },
  {
    id: 'b-decision',
    roles: '*',
    category: 'behavioral',
    levels: ['mid', 'senior'],
    question: 'Tell me about a difficult technical or business decision you made with incomplete information.',
    anchors: 'decision|decided|choose|chose|incomplete information|uncertain|trade off|tradeoff',
    points: [
      { label: 'Explained the options', terms: 'option|options|either|alternative|choice|choose between' },
      { label: 'Explained the trade offs', terms: 'trade off|tradeoff|risk|cost|downside|benefit|pros|cons' },
      { label: 'Showed how you limited the risk', terms: 'reversible|feature flag|pilot|small|rollback|deadline to revisit|checkpoint|experiment' },
      { label: 'Owned the decision and its result', terms: 'i decided|i chose|i made the call|result|turned out|outcome|learned' },
    ],
    model:
      'I had to choose between a managed queue service and running Kafka ourselves before we knew our real event volume. Kafka was more flexible but would need a dedicated engineer; the managed service was simpler but could get expensive at high volume. I chose the managed service because the decision was reversible: I wrapped it behind our own interface and set a cost alert. Eighteen months later volume was a tenth of our worst case, and the team never needed to switch. The lesson was to make reversible decisions quickly.',
    hints: STAR_HINTS,
    next: 'Tell me about a decision that turned out to be wrong. What did you do?',
  },
  {
    id: 'b-intro',
    roles: '*',
    category: 'behavioral',
    levels: ['entry', 'mid', 'senior'],
    question: 'Walk me through your background and why you are interested in this role.',
    anchors: 'background|experience|worked|role|interested|career|currently|studied|degree|years',
    points: [
      { label: 'Gave a short summary of your background', terms: 'i studied|degree|graduated|currently|i have|years|experience|worked at|i work' },
      { label: 'Highlighted experience relevant to this role', terms: 'built|led|worked on|experience with|experience in|skills|projects|responsible|years as|as a|mostly on|focused on|specialise|specialize|my work' },
      { label: 'Mentioned a concrete achievement', terms: 'achieved|launched|shipped|improved|reduced|increased|cut|grew|saved|percent|users|from|faster' },
      { label: 'Explained why this role, specifically', terms: 'interested|excited|this role|this company|your team|because|mission|product' },
    ],
    model:
      'I studied computer science and have spent three years as a backend developer at a logistics startup, mostly on our order and billing APIs. The work I enjoyed most was making slow systems fast: I cut our invoice generation time from forty minutes to three by moving it to a queue. I am interested in this role because your platform handles payments at a much larger scale, and the job description talks about reliability work, which is exactly where I want to grow.',
    hints: [
      'Keep it to about one minute: past, present, and why this role.',
      'Pick one achievement with a number.',
      'End with a reason that is specific to this company or team.',
    ],
    next: 'What do you expect to find hardest about this role?',
  },
  {
    id: 'b-priorities',
    roles: '*',
    category: 'behavioral',
    levels: ['mid', 'senior'],
    question: 'Tell me about a time two stakeholders wanted conflicting things from you. How did you decide?',
    anchors: 'stakeholder|stakeholders|conflicting|competing|priorities|both wanted|two teams|requests',
    points: [
      { label: 'Explained both requests', terms: 'asked for|requested|both|two teams|one team|the other|sales|support|marketing|finance|product team|one wanted|needed|wanted a' },
      { label: 'Tied the decision to goals or impact', terms: 'goal|impact|priority|business|revenue|users|okr|company|cost|hours|deal|customers|tickets|value|numbers' },
      { label: 'Brought the people together or escalated properly', terms: 'together|meeting|escalated|manager|agreed|aligned|discussion' },
      { label: 'Communicated the decision clearly', terms: 'explained|communicated|told|wrote|shared|transparent|showed|presented|together|stopgap|update' },
      { label: 'Gave the outcome', terms: 'result|outcome|delivered|shipped|later|both|agreed' },
    ],
    model:
      'Sales wanted a custom report for a big prospect and support wanted a fix for a bug that was generating tickets every day, and I could only do one that sprint. I estimated both and showed the numbers to both leads together: the bug cost about ten support hours a week, while the report might help one deal. We agreed with our director to fix the bug first and give sales a manual export as a stopgap. The bug fix cut tickets by 70 percent and the report shipped the following sprint.',
    hints: STAR_HINTS,
    next: 'What would you do if your manager disagreed with your priority?',
  },
];
