import type { Scenario } from './template';

// Every email here was written by hand. Blanks in [brackets] are filled in by
// the visitor; nothing is invented on their behalf.

const b = (...lines: string[]) => lines.join('\n');

export const SCENARIOS: Scenario[] = [
  // Job search
  {
    id: 'interview-thank-you',
    name: 'Thank you after an interview',
    group: 'Job search',
    blurb: 'Send the same day, while they still remember you.',
    tones: {
      friendly: {
        subject: 'Thanks for today, [Their name]',
        body: b(
          'Hi [Their name],',
          '',
          'Thanks for taking the time to talk with me today about the [Job title] role. I enjoyed hearing about [Something specific from the interview, e.g. the plan to rebuild checkout], and it made me even keener on the job.',
          '',
          'Our chat about [Topic you discussed] got me thinking about [A short idea you can add]. Happy to share more if it helps.',
          '',
          'Looking forward to hearing about next steps.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Thank you for the [Job title] interview',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you for meeting with me today to discuss the [Job title] role at [Company]. I appreciated learning about [Something specific from the interview], and it confirmed my interest in the position.',
          '',
          'I was especially interested in [Topic you discussed]. In my current role I have [A relevant result, e.g. led the move to a new billing system], and I would welcome the chance to bring that experience to your team.',
          '',
          'Please let me know if you need anything else from me. I look forward to hearing about the next steps.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Thank you: [Job title] interview',
        body: b(
          'Dear [Their name],',
          '',
          'Thank you for the opportunity to interview for the [Job title] position at [Company]. I am grateful for the time you and your colleagues gave me.',
          '',
          'Our discussion of [Topic you discussed] strengthened my interest in the role, and I believe my experience with [A relevant result] would allow me to contribute from the outset.',
          '',
          'Should you require any further information, I would be glad to provide it. I look forward to hearing from you.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'application-follow-up',
    name: 'Follow up on a job application',
    group: 'Job search',
    blurb: 'A polite nudge after a week or two of silence.',
    tones: {
      friendly: {
        subject: 'Checking in on my [Job title] application',
        body: b(
          'Hi [Their name],',
          '',
          'I applied for the [Job title] role on [Date you applied] and wanted to check where things stand. I am still very interested, especially in [What draws you to the role].',
          '',
          'If it helps, I can send work samples or answer any questions.',
          '',
          'Thanks,',
          '[Your name]',
        ),
      },
      professional: {
        subject: '[Job title] application: following up',
        body: b(
          'Hi [Their name],',
          '',
          'I applied for the [Job title] position at [Company] on [Date you applied] and wanted to follow up on the status of my application.',
          '',
          'I remain very interested in the role, particularly [What draws you to the role]. Since applying I have [Something new since applying, e.g. finished a related certification], which I think adds to my fit.',
          '',
          'Could you let me know where the process stands and whether you need anything else from me?',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Application for [Job title]: status inquiry',
        body: b(
          'Dear [Their name],',
          '',
          'I submitted my application for the [Job title] position at [Company] on [Date you applied]. I am writing to ask about its status and to confirm my continued interest.',
          '',
          'I would be pleased to provide any further documents or references you may require.',
          '',
          'Thank you for your time and consideration.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'accept-offer',
    name: 'Accept a job offer',
    group: 'Job search',
    blurb: 'Say yes and confirm the details in writing.',
    tones: {
      friendly: {
        subject: 'Yes, I accept the [Job title] offer',
        body: b(
          'Hi [Their name],',
          '',
          'I am happy to say yes. I accept the offer for the [Job title] role, and I cannot wait to get started.',
          '',
          'To confirm what we agreed: a salary of [Salary] and a start date of [Start date]. Let me know if anything needs to change or if there is paperwork I should fill in before then.',
          '',
          'Thanks again for everything so far.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Acceptance of the [Job title] offer',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you for the offer for the [Job title] position at [Company]. I am pleased to accept.',
          '',
          'As discussed, my starting salary will be [Salary] and my start date will be [Start date]. Please let me know what you need from me before then, and whether there is anything I should prepare.',
          '',
          'I look forward to joining the team.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Formal acceptance: [Job title] position',
        body: b(
          'Dear [Their name],',
          '',
          'I am writing to formally accept the offer of the [Job title] position at [Company], as set out in your letter of [Offer date].',
          '',
          'I confirm the agreed annual salary of [Salary] and a start date of [Start date]. Please let me know which documents you need from me, and I will return them promptly.',
          '',
          'Thank you for this opportunity. I look forward to working with you.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'decline-offer',
    name: 'Decline a job offer',
    group: 'Job search',
    blurb: 'Turn it down kindly and keep the door open.',
    tones: {
      friendly: {
        subject: 'About the [Job title] offer',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you so much for the offer and for how kind everyone was during the process. After a lot of thought, I have decided not to accept. [Short honest reason, e.g. I have taken a role closer to home].',
          '',
          'I really enjoyed meeting the team and hope our paths cross again.',
          '',
          'All the best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: '[Job title] offer: my decision',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you for offering me the [Job title] position at [Company]. I appreciate the time you and the team put into the process.',
          '',
          'After careful thought, I have decided to decline the offer. [Short honest reason]. It was not an easy decision.',
          '',
          'I hope we can stay in touch, and I wish you and the team every success.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Response to the [Job title] offer',
        body: b(
          'Dear [Their name],',
          '',
          'Thank you for offering me the position of [Job title] at [Company]. After careful consideration, I must respectfully decline.',
          '',
          'I am grateful for the courtesy shown to me throughout the process, and I hold [Company] in high regard.',
          '',
          'I wish you and your organization continued success.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'referral',
    name: 'Ask for a referral',
    group: 'Job search',
    blurb: 'Make it easy for a contact to say yes, or no.',
    tones: {
      friendly: {
        subject: 'A small favor: [Job title] at [Company]',
        body: b(
          'Hi [Their name],',
          '',
          'I saw that [Company] is hiring a [Job title] and I am planning to apply. Since you work there, would you be comfortable referring me?',
          '',
          'Here is the posting: [Link to the job posting]. In short, I think I would fit because [One line on why you fit].',
          '',
          'No pressure at all if it is not a good time. I have attached my resume in case it is useful.',
          '',
          'Thanks either way,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Referral request: [Job title] at [Company]',
        body: b(
          'Hi [Their name],',
          '',
          'I hope things are going well at [Company]. I am applying for the [Job title] role ([Link to the job posting]) and wanted to ask whether you would be willing to refer me.',
          '',
          'My background in [One line on why you fit] lines up closely with what the team needs. I have attached my resume, and I can send a short summary you can forward.',
          '',
          'I completely understand if you are not able to. Thank you for considering it.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Request for a referral: [Job title]',
        body: b(
          'Dear [Their name],',
          '',
          'I intend to apply for the [Job title] position at [Company] ([Link to the job posting]), and I would be grateful if you would consider referring me.',
          '',
          'I believe my experience in [One line on why you fit] would allow me to contribute to the team. My resume is attached for your reference.',
          '',
          'Please feel free to decline if this is not appropriate. Thank you for your time.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'resignation',
    name: 'Resign from your job',
    group: 'Job search',
    blurb: 'Clear notice, a thank you and a handover plan.',
    tones: {
      friendly: {
        subject: 'Some news: I am moving on',
        body: b(
          'Hi [Their name],',
          '',
          'I wanted you to hear this from me first. I have decided to leave my role as [Job title], and my last day will be [Last working day].',
          '',
          'I have learned a lot here and really valued working with you. Over the next few weeks I will make sure [Work you will hand over] is handed over properly.',
          '',
          'Thank you for everything.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Resignation: [Your name]',
        body: b(
          'Hi [Their name],',
          '',
          'Please accept this email as notice of my resignation from my position as [Job title]. My last working day will be [Last working day], in line with my notice period.',
          '',
          'I am grateful for the opportunities I have had here, especially [Something you appreciated]. I will do everything I can to make the handover smooth, including [Work you will hand over].',
          '',
          'Thank you for your support.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Letter of resignation',
        body: b(
          'Dear [Their name],',
          '',
          'I am writing to formally resign from my position as [Job title] at [Company], effective [Last working day].',
          '',
          'I would like to thank you for the opportunities for professional development I have had during my employment. I will ensure a complete handover of my responsibilities, including [Work you will hand over], before I leave.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },

  // At work
  {
    id: 'meeting-request',
    name: 'Request a meeting',
    group: 'At work',
    blurb: 'Say why, how long, and offer real times.',
    tones: {
      friendly: {
        subject: 'Can we find 30 minutes for [Topic]?',
        body: b(
          'Hi [Their name],',
          '',
          'Could we find 30 minutes this week to talk about [Topic]? I would like to [What you want to get out of it, e.g. agree on the launch plan].',
          '',
          'I am free [Two or three time options]. If none of those work, send me a time that suits you.',
          '',
          'Thanks,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Meeting request: [Topic]',
        body: b(
          'Hi [Their name],',
          '',
          'I would like to set up a [Meeting length, e.g. 30 minute] meeting to discuss [Topic]. The goal is to [What you want to get out of it].',
          '',
          'Would any of these times work for you? [Two or three time options]',
          '',
          'I can send a short agenda in advance if that helps.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Request for a meeting regarding [Topic]',
        body: b(
          'Dear [Their name],',
          '',
          'I am writing to request a meeting to discuss [Topic]. I would like to [What you want to get out of it].',
          '',
          'I am available at the following times: [Two or three time options]. I would be happy to adjust to your schedule if none of these are convenient.',
          '',
          'Thank you for your consideration.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'deadline-extension',
    name: 'Ask for more time',
    group: 'At work',
    blurb: 'Ask early, give a reason and a new date.',
    tones: {
      friendly: {
        subject: 'More time for [Task]?',
        body: b(
          'Hi [Their name],',
          '',
          'I am going to need a bit more time on [Task]. [Honest reason, e.g. the data arrived two days late].',
          '',
          'Would [New date] work instead? In the meantime I can send you [What you can deliver now] so you are not waiting on everything.',
          '',
          'Thanks for understanding,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Request to move the [Task] deadline to [New date]',
        body: b(
          'Hi [Their name],',
          '',
          'I am writing to ask for an extension on [Task], which is currently due [Current deadline]. [Honest reason].',
          '',
          'I can deliver the finished work by [New date]. To keep things moving, I can share [What you can deliver now] before then.',
          '',
          'Please let me know if this works or if another date suits you better.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Request for a deadline extension: [Task]',
        body: b(
          'Dear [Their name],',
          '',
          'I respectfully request an extension of the deadline for [Task], which is currently set for [Current deadline]. [Honest reason].',
          '',
          'I propose a revised deadline of [New date], and I will provide [What you can deliver now] in the meantime.',
          '',
          'I apologize for any inconvenience and would be grateful for your confirmation.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'project-delay',
    name: 'Tell someone a project is late',
    group: 'At work',
    blurb: 'Bad news early, with the new date and your plan.',
    tones: {
      friendly: {
        subject: '[Project] update: new date is [New date]',
        body: b(
          'Hi [Their name],',
          '',
          'I wanted to let you know early that [Project] will not be ready on [Original date]. [What caused the delay].',
          '',
          'The new date is [New date]. Here is what we are doing to hit it: [What you are doing about it].',
          '',
          'Sorry for the change. Let me know if you want to talk it through.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: '[Project] timeline update',
        body: b(
          'Hi [Their name],',
          '',
          'I want to give you an early update on [Project]. We will not meet the [Original date] date because [What caused the delay].',
          '',
          'Our revised delivery date is [New date]. To protect that date we are [What you are doing about it].',
          '',
          'I am sorry for the delay. Would a short call this week be useful to go through the impact on your side?',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Revised delivery date for [Project]',
        body: b(
          'Dear [Their name],',
          '',
          'I regret to inform you that [Project] will not be delivered by [Original date] as planned. The delay is due to [What caused the delay].',
          '',
          'We now expect to complete the work by [New date]. To ensure this, we are [What you are doing about it].',
          '',
          'Please accept our apologies. I would be glad to discuss the revised plan with you, and I would appreciate your confirmation that the new date is acceptable.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'status-update',
    name: 'Send a status update',
    group: 'At work',
    blurb: 'Done, next, and what you need from them.',
    tones: {
      friendly: {
        subject: 'Quick update on [Project]',
        body: b(
          'Hi [Their name],',
          '',
          'Here is where [Project] stands this week.',
          '',
          'Done: [What is finished]',
          'Next: [What comes next]',
          'Blocked on: [Anything you need, or nothing]',
          '',
          'Let me know if you want more detail on any of it.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: '[Project] status update, [Date]',
        body: b(
          'Hi [Their name],',
          '',
          'Here is this week’s update on [Project].',
          '',
          'Completed: [What is finished]',
          'In progress: [What comes next]',
          'Needs your input: [Anything you need, or nothing]',
          '',
          'Overall we are [On track, at risk or behind] for [Deadline]. Let me know if you have any questions.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Status report: [Project], [Date]',
        body: b(
          'Dear [Their name],',
          '',
          'Please find below the current status of [Project].',
          '',
          'Completed work: [What is finished]',
          'Planned work: [What comes next]',
          'Matters requiring your attention: [Anything you need, or nothing]',
          '',
          'The project remains [On track, at risk or behind] against the deadline of [Deadline]. Please let me know if you require further detail.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'decline-request',
    name: 'Say no to a request',
    group: 'At work',
    blurb: 'A clear no, a reason, and an alternative.',
    tones: {
      friendly: {
        subject: 'Re: [Their request]',
        body: b(
          'Hi [Their name],',
          '',
          'Thanks for thinking of me for [Their request]. I am going to have to pass this time because [Short reason, e.g. I am fully booked until March].',
          '',
          'Could [An alternative, e.g. Sara help, or I could look at it next month] work instead?',
          '',
          'Hope it goes well,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Re: [Their request]',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you for asking me to help with [Their request]. Unfortunately I am not able to take it on, as [Short reason].',
          '',
          'I would suggest [An alternative] instead. Let me know if you would like me to make an introduction.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Re: [Their request]',
        body: b(
          'Dear [Their name],',
          '',
          'Thank you for your request regarding [Their request]. I regret that I am unable to assist on this occasion, as [Short reason].',
          '',
          'You may wish to consider [An alternative]. Please let me know if I can help in another way.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'out-of-office',
    name: 'Out of office reply',
    group: 'At work',
    blurb: 'When you are back and who to contact meanwhile.',
    tones: {
      friendly: {
        subject: 'Out of office until [Return date]',
        body: b(
          'Hi,',
          '',
          'Thanks for your email. I am away until [Return date] and only checking email now and then.',
          '',
          'If it is urgent, please contact [Backup contact name] at [Backup contact email]. Otherwise I will reply when I am back.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Out of office: back [Return date]',
        body: b(
          'Hello,',
          '',
          'Thank you for your message. I am out of the office from [First day away] until [Return date] with limited access to email.',
          '',
          'For urgent matters, please contact [Backup contact name] at [Backup contact email]. I will respond to your email after I return.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Automatic reply: absent until [Return date]',
        body: b(
          'Hello,',
          '',
          'Thank you for your email. I am currently out of the office and will return on [Return date].',
          '',
          'During my absence, please direct urgent matters to [Backup contact name] at [Backup contact email]. I will attend to your message on my return.',
          '',
          'Yours faithfully,',
          '[Your name]',
        ),
      },
    },
  },

  // Clients and freelance
  {
    id: 'cold-intro',
    name: 'Introduce yourself to a new contact',
    group: 'Clients and freelance',
    blurb: 'Short, specific about them, and one easy ask.',
    tones: {
      friendly: {
        subject: 'Hello from a fellow [Shared interest or field]',
        body: b(
          'Hi [Their name],',
          '',
          'I am [Your name], a [What you do]. I came across [How you found them, e.g. your talk on design systems] and wanted to say hello.',
          '',
          'I noticed [Something specific about their work or company], and I think I could help with [What you could help with]. For example, I recently [A short proof, e.g. cut a client’s page load time in half].',
          '',
          'Would you be open to a 15 minute chat next week?',
          '',
          'Thanks,',
          '[Your name]',
        ),
      },
      professional: {
        subject: '[What you could help with] for [Company]',
        body: b(
          'Hi [Their name],',
          '',
          'My name is [Your name], and I am a [What you do]. I am reaching out because [How you found them].',
          '',
          'I noticed [Something specific about their work or company]. I help teams like yours with [What you could help with], and recently [A short proof].',
          '',
          'Would you be open to a short call to see if this is useful for [Company]? If not, no problem at all.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Introduction: [Your name], [What you do]',
        body: b(
          'Dear [Their name],',
          '',
          'Please allow me to introduce myself. I am [Your name], a [What you do]. I am writing because [How you found them].',
          '',
          'Having followed [Something specific about their work or company], I believe I could assist with [What you could help with]. Most recently, [A short proof].',
          '',
          'Would you be available for a brief conversation at a time convenient for you?',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'invoice-reminder',
    name: 'Remind a client about an invoice',
    group: 'Clients and freelance',
    blurb: 'Facts first: number, amount, due date, how to pay.',
    tones: {
      friendly: {
        subject: 'Invoice [Invoice number] was due [Due date]',
        body: b(
          'Hi [Their name],',
          '',
          'A quick reminder that invoice [Invoice number] for [Amount] was due on [Due date]. I have attached it again in case it got buried.',
          '',
          'You can pay by [Payment method]. Let me know if anything is unclear or if you need it sent to someone else.',
          '',
          'Thanks,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Payment reminder: invoice [Invoice number]',
        body: b(
          'Hi [Their name],',
          '',
          'This is a reminder that invoice [Invoice number] for [Amount], issued on [Invoice date], was due on [Due date]. I have attached a copy.',
          '',
          'Payment can be made by [Payment method]. Could you let me know when I can expect it, or tell me if there is a problem I can help with?',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Overdue invoice [Invoice number]',
        body: b(
          'Dear [Their name],',
          '',
          'According to our records, invoice [Invoice number] for [Amount], due on [Due date], remains unpaid. A copy is attached for your reference.',
          '',
          'I would be grateful if you could arrange payment by [Payment method] within [Number of days] days, or contact me if there is any issue with the invoice.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'proposal-follow-up',
    name: 'Follow up on a proposal',
    group: 'Clients and freelance',
    blurb: 'Offer to answer questions or adjust the scope.',
    tones: {
      friendly: {
        subject: 'Any thoughts on the [Project] proposal?',
        body: b(
          'Hi [Their name],',
          '',
          'I sent over the proposal for [Project] on [Date sent] and wanted to see if you had a chance to look.',
          '',
          'Happy to adjust the scope or talk it through on a quick call. Would [Suggested day] work?',
          '',
          'Thanks,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Following up: [Project] proposal',
        body: b(
          'Hi [Their name],',
          '',
          'I am following up on the proposal for [Project] that I sent on [Date sent]. Do you have any questions, or is there anything you would like me to adjust?',
          '',
          'If it helps, I can walk you through it on a short call on [Suggested day].',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Proposal for [Project]',
        body: b(
          'Dear [Their name],',
          '',
          'Further to my proposal for [Project] dated [Date sent], I would be pleased to answer any questions you may have.',
          '',
          'Would [Suggested day] be convenient for a short discussion of the proposal?',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },

  // Everyday
  {
    id: 'no-reply-follow-up',
    name: 'Follow up when you got no reply',
    group: 'Everyday',
    blurb: 'Reply on the same thread so they see the history.',
    tones: {
      friendly: {
        subject: 'Re: [Original subject]',
        body: b(
          'Hi [Their name],',
          '',
          'Bringing this back to the top of your inbox in case it got lost. I am still keen to hear your thoughts on [What you asked about].',
          '',
          'If now is not a good time, let me know when to check back.',
          '',
          'Thanks,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Re: [Original subject]',
        body: b(
          'Hi [Their name],',
          '',
          'I am following up on my email from [Date of first email] about [What you asked about]. I would appreciate an update when you have a moment.',
          '',
          'If someone else is better placed to help, could you point me to them?',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Re: [Original subject]',
        body: b(
          'Dear [Their name],',
          '',
          'I am writing further to my email of [Date of first email] regarding [What you asked about]. I would be grateful for your response.',
          '',
          'Should this matter be better directed to a colleague, could you kindly share their contact details?',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'apology',
    name: 'Apologize for a mistake',
    group: 'Everyday',
    blurb: 'Own it, name the effect, say what you fixed.',
    tones: {
      friendly: {
        subject: 'Sorry about [What went wrong]',
        body: b(
          'Hi [Their name],',
          '',
          'I am sorry about [What went wrong]. That was my mistake, and I know it [The effect on them, e.g. cost you an afternoon].',
          '',
          'I have already [What you have done to fix it], and from now on I will [What you will do differently].',
          '',
          'Thanks for your patience,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Apology for [What went wrong]',
        body: b(
          'Hi [Their name],',
          '',
          'I want to apologize for [What went wrong]. I take full responsibility, and I understand this [The effect on them].',
          '',
          'To put it right, I have [What you have done to fix it]. To make sure it does not happen again, I will [What you will do differently].',
          '',
          'Please let me know if there is anything else I can do.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'Apology regarding [What went wrong]',
        body: b(
          'Dear [Their name],',
          '',
          'Please accept my sincere apologies for [What went wrong]. I recognize that this [The effect on them].',
          '',
          'I have since [What you have done to fix it], and I will [What you will do differently] so that it does not happen again.',
          '',
          'Thank you for your understanding.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
  {
    id: 'thank-you',
    name: 'Say thank you',
    group: 'Everyday',
    blurb: 'Name what they did and the difference it made.',
    tones: {
      friendly: {
        subject: 'Thank you for [What they did]',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you for [What they did]. It made a real difference: [The result, e.g. we shipped on time].',
          '',
          'I owe you one. Let me know if I can ever return the favor.',
          '',
          'Best,',
          '[Your name]',
        ),
      },
      professional: {
        subject: 'Thank you for [What they did]',
        body: b(
          'Hi [Their name],',
          '',
          'Thank you for [What they did]. Your help meant [The result], and I really appreciate the time you put in.',
          '',
          'If I can ever return the favor, please let me know.',
          '',
          'Best regards,',
          '[Your name]',
        ),
      },
      formal: {
        subject: 'With thanks',
        body: b(
          'Dear [Their name],',
          '',
          'I would like to express my sincere thanks for [What they did]. Your assistance resulted in [The result], and it is greatly appreciated.',
          '',
          'Please let me know if I can ever assist you in return.',
          '',
          'Yours sincerely,',
          '[Your name]',
        ),
      },
    },
  },
];

export const SCENARIO_BY_ID: Record<string, Scenario> = Object.fromEntries(SCENARIOS.map((s) => [s.id, s]));
