"""
Build the Salary Estimator data from the official BLS wage files.

Source: US Bureau of Labor Statistics, Occupational Employment and Wage
Statistics (OEWS). Download the National, State and Metropolitan area XLSX
zips from https://www.bls.gov/oes/tables.htm and put them in data-src/bls/.

Run from the project root once a year, after BLS publishes new estimates
(usually in spring):

    pip install pandas openpyxl
    python scripts/build-salary-data.py

Then update DATA_PERIOD and DATA_RELEASED below and commit the changed files in
public/data/salary/ and src/lib/salary/national.ts.

The job list comes from src/lib/salary/jobs.ts, so adding a job there and
rerunning this script is all that is needed.
"""

import io
import json
import re
import sys
import zipfile
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data-src" / "bls"
OUT_DIR = ROOT / "public" / "data" / "salary"
NATIONAL_TS = ROOT / "src" / "lib" / "salary" / "national.ts"
JOBS_TS = ROOT / "src" / "lib" / "salary" / "jobs.ts"

DATA_PERIOD = "May 2025"
DATA_RELEASED = "2026-05-15"
YEAR_CODE = "25"  # oesm25*.zip

# BLS marks wages at or above its top published value with "#".
# Stored as -1 so the page can show "$239,200 or more".
TOP_CODE = -1
PCTS = ["A_PCT10", "A_PCT25", "A_MEDIAN", "A_PCT75", "A_PCT90"]


def wage(v):
    s = str(v).strip()
    if s == "#":
        return TOP_CODE
    try:
        return int(round(float(s.replace(",", ""))))
    except ValueError:
        return None  # "*" means BLS did not publish this estimate


def count(v):
    try:
        return int(round(float(str(v).replace(",", ""))))
    except ValueError:
        return None  # "**" means no employment estimate


def read_zip(name):
    path = SRC / f"oesm{YEAR_CODE}{name}.zip"
    if not path.exists():
        sys.exit(f"Missing {path}. Download it from https://www.bls.gov/oes/tables.htm")
    frames = []
    with zipfile.ZipFile(path) as z:
        for member in z.namelist():
            if member.endswith(".xlsx") and "_dl" in member:
                with z.open(member) as f:
                    frames.append(pd.read_excel(io.BytesIO(f.read()), dtype=str))
    if not frames:
        sys.exit(f"No data sheet found in {path}")
    return pd.concat(frames, ignore_index=True)


def main():
    codes = re.findall(r'code:\s*"(\d{2}-\d{4})"', JOBS_TS.read_text(encoding="utf-8"))
    if not codes:
        sys.exit("No job codes found in src/lib/salary/jobs.ts")

    print("Reading BLS files, this takes about a minute...")
    df = pd.concat([read_zip("nat"), read_zip("st"), read_zip("ma")], ignore_index=True)
    df.columns = [c.upper() for c in df.columns]
    df = df[df["OCC_CODE"].isin(codes)]
    # Some occupations appear twice (broad and detailed level). Keep one row each.
    df = df.assign(_d=(df["O_GROUP"].str.lower() != "detailed")).sort_values("_d")
    df = df.drop_duplicates(["AREA", "OCC_CODE"]).drop(columns="_d")

    missing = sorted(set(codes) - set(df["OCC_CODE"]))
    if missing:
        sys.exit(f"These codes are not in the BLS files: {missing}")

    # Area index: US first, then states and territories, then metro and
    # nonmetro areas, each sorted by name.
    areas = (
        df[["AREA", "AREA_TITLE", "AREA_TYPE", "PRIM_STATE"]]
        .drop_duplicates("AREA")
        .assign(T=lambda d: d["AREA_TYPE"].astype(int))
    )
    areas["ORDER"] = areas["T"].map({1: 0, 2: 1, 3: 1, 4: 2, 6: 2})
    areas = areas.sort_values(["ORDER", "AREA_TITLE"])
    area_list = [[r.AREA, r.AREA_TITLE, int(r.T), r.PRIM_STATE] for r in areas.itertuples()]

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "areas.json").write_text(
        json.dumps({"period": DATA_PERIOD, "areas": area_list}, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )

    national = {}
    for code in codes:
        rows = df[df["OCC_CODE"] == code]
        title = rows["OCC_TITLE"].iloc[0]
        wages = {}
        for r in rows.itertuples():
            p = [wage(getattr(r, c)) for c in PCTS]
            wages[r.AREA] = p + [wage(r.A_MEAN), count(r.TOT_EMP)]
        us = wages.get("99")
        if not us or any(v is None or v == TOP_CODE for v in us[:6]):
            sys.exit(f"Incomplete national wages for {code}")
        national[code] = {"title": title, "p": us[:5], "mean": us[5], "emp": us[6], "areas": len(wages)}
        (OUT_DIR / f"{code}.json").write_text(
            json.dumps({"code": code, "title": title, "period": DATA_PERIOD, "w": wages}, separators=(",", ":")),
            encoding="utf-8",
        )

    lines = [
        "// Generated by scripts/build-salary-data.py from the BLS OEWS files. Do not edit by hand.",
        "// Annual wages in US dollars: 10th, 25th, 50th (median), 75th and 90th percentile.",
        "",
        f'export const DATA_PERIOD = "{DATA_PERIOD}";',
        f'export const DATA_RELEASED = "{DATA_RELEASED}";',
        f"export const AREA_COUNT = {len(area_list)};",
        "export const AREA_COUNTS = { states: %d, territories: %d, metros: %d, nonmetros: %d };"
        % tuple(sum(1 for a in area_list if a[2] == t) for t in (2, 3, 4, 6)),
        "",
        "export interface NationalWage {",
        "  title: string;",
        "  p: [number, number, number, number, number];",
        "  mean: number;",
        "  emp: number | null;",
        "  areas: number;",
        "}",
        "",
        "export const NATIONAL: Record<string, NationalWage> = {",
    ]
    for code, n in national.items():
        lines.append(
            f'  "{code}": {{ title: {json.dumps(n["title"])}, p: {json.dumps(n["p"])}, '
            f'mean: {n["mean"]}, emp: {json.dumps(n["emp"])}, areas: {n["areas"]} }},'
        )
    lines += ["};", ""]
    NATIONAL_TS.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {len(codes)} job files and {len(area_list)} areas to {OUT_DIR}")


if __name__ == "__main__":
    main()
